In [37]:
x = 10
y = -3

In [38]:
x

10

In [39]:
print(type(x))

<class 'int'>

In [40]:
a = 3.14
b = 10.0

In [41]:
a

3.14

In [42]:
print(type(a))

<class 'float'>

In [43]:
name = "Alice"
city = 'Yerevan'

In [44]:
name

'Alice'

In [45]:
print(type(name))

<class 'str'>

In [46]:
is_active = True
is_complete = False

In [47]:
is_active

True

In [48]:
print(type(is_active))

<class 'bool'>

In [49]:
x = 10
x > 5

True

In [50]:
x = 10

In [51]:
x

10

In [52]:
count = 100

In [53]:
count

100

In [54]:
price = 19.99

In [55]:
price

19.99

In [56]:
customer_name = "Alice"

In [57]:
customer_name

'Alice'

In [58]:
is_active = True

In [59]:
is_active

True

In [60]:
type(price)

float

In [61]:
x = 20

In [62]:
x

20

In [63]:
x = 5

In [64]:
x

5

In [65]:
price = 100
quantity = 3

In [66]:
revenue = price * quantity

In [67]:
revenue

300

In [68]:
total_sales = 500
customer_id = 101
average_price = 19.5

In [69]:
r = 100
t = 0.2

In [70]:
total = r * (1 + t)

In [71]:
total

120.0

In [72]:
100 > 50
100 == 50
100 != 50

True

In [73]:
print((100 > 50) and (20 < 30))

True

In [74]:
sales = [100, 200, 150, 200]

In [75]:
sales

[100, 200, 150, 200]

In [76]:
sales[0]
sales[-1]

200

In [77]:
sales.append(300)
sales[1] = 250

In [78]:
sales

[100, 250, 150, 200, 300]

In [79]:
sales.remove(150)

In [80]:
sales

[100, 250, 200, 300]

In [81]:
len(sales)

4

In [82]:
total = 0
for value in sales:
    total += value

In [83]:
total

850

In [84]:
coordinates = (40.18, 44.51)

In [85]:
coordinates

(40.18, 44.51)

In [86]:
customer_ids = {1, 2, 3, 3, 4}

In [87]:
customer_ids

{1, 2, 3, 4}

In [88]:
segment_a = {1, 2, 3}
segment_b = {3, 4, 5}

In [89]:
segment_a.intersection(segment_b)

{3}

In [90]:
customer = {
    "name": "Anna",
    "revenue": 150,
    "city": "Yerevan"
}

In [91]:
customer

{'name': 'Anna', 'revenue': 150, 'city': 'Yerevan'}

In [92]:
customer["revenue"]

150

In [93]:
customer["segment"] = "Premium"
customer["revenue"] = 200

In [94]:
customer

{'name': 'Anna', 'revenue': 200, 'city': 'Yerevan', 'segment': 'Premium'}

In [95]:
del customer["city"]

In [96]:
customer

{'name': 'Anna', 'revenue': 200, 'segment': 'Premium'}

In [97]:
customers = [
    {"name": "Anna", "revenue": 150},
    {"name": "David", "revenue": 220},
    {"name": "Mariam", "revenue": 90}
]

In [98]:
customers

[{'name': 'Anna', 'revenue': 150},
 {'name': 'David', 'revenue': 220},
 {'name': 'Mariam', 'revenue': 90}]

### Arithmetic Operations

In [99]:
r = 100
t = 0.2

In [100]:
total = r * (1 + t)

In [101]:
total

120.0

### List

In [102]:
sales = [100, 200, 150, 200]

In [103]:
sales

[100, 200, 150, 200]

##### Access elements:

In [104]:
sales[0]
sales[-1]

200

#### Modify elements:

In [105]:
sales.append(300)
sales[1] = 250

In [106]:
sales

[100, 250, 150, 200, 300]

#### Remove elements:

In [107]:
sales.remove(150)

In [108]:
sales

[100, 250, 200, 300]

#### Length of the list:

In [109]:
len(sales)

4

#### Analytical Context

In [110]:
total = 0
for value in sales:
    total += value

In [111]:
total

850

### Tuple

In [112]:
coordinates = (40.18, 44.51)

In [113]:
coordinates

(40.18, 44.51)

### Set

In [114]:
customer_ids = {1, 2, 3, 3, 4}

In [115]:
customer_ids

{1, 2, 3, 4}

#### Analytical use case:

In [116]:
segment_a = {1, 2, 3}
segment_b = {3, 4, 5}

In [117]:
segment_a.intersection(segment_b)

{3}

### Dictionary

In [118]:
customer = {
    "name": "Anna",
    "revenue": 150,
    "city": "Yerevan"
}

In [119]:
customer

{'name': 'Anna', 'revenue': 150, 'city': 'Yerevan'}

#### Add or update:

In [120]:
customer["segment"] = "Premium"
customer["revenue"] = 200

In [121]:
customer

{'name': 'Anna', 'revenue': 200, 'city': 'Yerevan', 'segment': 'Premium'}

#### Remove:

In [2]:
del customer["city"]

NameError: name 'customer' is not defined

#### From Dictionary to Structured Data

In [123]:
customers = [
    {"name": "Anna", "revenue": 150},
    {"name": "David", "revenue": 220},
    {"name": "Mariam", "revenue": 90}
]

In [124]:
customers

[{'name': 'Anna', 'revenue': 150},
 {'name': 'David', 'revenue': 220},
 {'name': 'Mariam', 'revenue': 90}]

### Transition to Pandas
#### Creating a DataFrame

In [1]:
import pandas as pd

data = {
    "name": ["Anna", "David", "Mariam"],
    "revenue": [150, 220, 90],
    "city": ["Yerevan", "Tbilisi", "Warsaw"]
}

df = pd.DataFrame(data)
df

     name  revenue     city
0    Anna      150  Yerevan
1   David      220  Tbilisi
2  Mariam       90   Warsaw

In [3]:
df.info()
df.shape
df.columns

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     3 non-null      str
 1   revenue  3 non-null      int64
 2   city     3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

Index(['name', 'revenue', 'city'], dtype='str')

#### Basic DataFrame Manipulation
### Selecting Columns

In [4]:
df["revenue"]
df[["name", "revenue"]]

     name  revenue
0    Anna      150
1   David      220
2  Mariam       90

#### Adding a column

In [5]:
t = 0.2
df["revenue_after_tax"] = df["revenue"] * (1 - t)
df

     name  revenue     city  revenue_after_tax
0    Anna      150  Yerevan              120.0
1   David      220  Tbilisi              176.0
2  Mariam       90   Warsaw               72.0

#### Removing a Column

In [6]:
df.drop("city", axis=1)

     name  revenue  revenue_after_tax
0    Anna      150              120.0
1   David      220              176.0
2  Mariam       90               72.0

##### To modify permanently:

In [7]:
df = df.drop("city", axis=1)
df

     name  revenue  revenue_after_tax
0    Anna      150              120.0
1   David      220              176.0
2  Mariam       90               72.0

##### Filtering Rows

In [8]:
df[df["revenue"] > 100]

    name  revenue  revenue_after_tax
0   Anna      150              120.0
1  David      220              176.0

##### Updating values

In [9]:
df.loc[df["revenue"] < 100, "segment"] = "Low"
df.loc[df["revenue"] >= 100, "segment"] = "High"
df

     name  revenue  revenue_after_tax segment
0    Anna      150              120.0    High
1   David      220              176.0    High
2  Mariam       90               72.0     Low

#### Conditional Statements
##### The Basic if Statement

In [10]:
revenue = 150

if revenue > 100:
    print("High revenue")
else:
    print("Normal revenue")

High revenue

##### Indentation

In [12]:
revenue = 150

if revenue > 100:
    print("High revenue")

print("Analysis complete")

High revenue
Analysis complete

##### Using elif for Multiple Conditions

In [13]:
revenue = 180

if revenue > 200:
    print("Very high revenue")
elif revenue > 100:
    print("High revenue")
elif revenue > 50:
    print("Medium revenue")
else:
    print("Low revenue")

High revenue

##### Boolean Expressions and Comparison Operators

In [15]:
100 > 50
100 == 50
100 != 50

True

##### Combining Conditions with Logical Operators

In [16]:
revenue = 150
is_active = True

if revenue > 100 and is_active:
    print("Target customer")

Target customer

In [17]:
is_active = False

if not is_active:
    print("Customer is inactive")

Customer is inactive

##### Nested Conditional Statements

In [18]:
revenue = 150
region = "EU"

if revenue > 100:
    if region == "EU":
        print("High EU revenue")
    else:
        print("High non-EU revenue")

High EU revenue

#### Loops
##### The Basic for Loop

In [19]:
sales = [100, 200, 150]

for value in sales:
    print(value)

100
200
150

##### Loop With Accumulation

In [20]:
sales = [100, 200, 150]

total = 0

for value in sales:
    total = total + value

total

450

##### Loop With Conditional Logic

In [21]:
sales = [100, 200, 150, 50]

for value in sales:
    if value > 120:
        print("High sale:", value)

High sale: 200
High sale: 150

##### Looping Over Dictionaries
###### Loops are not limited to lists.

In [22]:
customer = {
    "name": "Anna",
    "revenue": 150,
    "city": "Yerevan"
}

for key in customer:
    print(key, ":", customer[key])

name : Anna
revenue : 150
city : Yerevan

###### You can also iterate over key–value pairs:

In [23]:
for key, value in customer.items():
    print(key, value)

name Anna
revenue 150
city Yerevan

#### The range() Function

In [24]:
for i in range(5):
    print(i)

0
1
2
3
4

##### Nested Loops

In [25]:
for i in range(3):
    for j in range(2):
        print("i =", i, ", j =", j)

i = 0 , j = 0
i = 0 , j = 1
i = 1 , j = 0
i = 1 , j = 1
i = 2 , j = 0
i = 2 , j = 1

#### List Comprehension
##### Basic Structure

In [27]:
new_list = [expression for item in iterable]

NameError: name 'iterable' is not defined

##### Equivalent traditional loop:

##### Now using list comprehension:

##### With Conditional Filtering
###### You can add a condition:

In [29]:
sales = [100, 200, 150, 50]

high_sales = [value for value in sales if value > 120]
high_sales

[200, 150]

###### Traditional version:

In [30]:
high_sales = []

for value in sales:
    if value > 120:
        high_sales.append(value)

high_sales

[200, 150]

##### Conditional Expression Inside Comprehension

In [31]:
sales = [100, 200, 150, 50]

labels = ["High" if value > 120 else "Low" for value in sales]
labels

['Low', 'High', 'High', 'Low']

#### Train Yourself

##### 1.Create a new list with revenues after applying 10% tax.

In [41]:
revenues = [120, 250, 80, 310, 95]

revenues_after_tax = [r * 0.9 for r in revenues]

print(revenues_after_tax)

[108.0, 225.0, 72.0, 279.0, 85.5]

##### 2. Create a list containing only revenues greater than 100.

In [42]:
revenues = [120, 250, 80, 310, 95]

greater_than_100 = [r for r in revenues if r > 100]

print(greater_than_100)

[120, 250, 310]

##### 3.Create a list labeling each revenue as "High" if > 200, otherwise "Normal".

In [43]:
revenues = [120, 250, 80, 310, 95]

labels = ["High" if r > 200 else "Normal" for r in revenues]

print(labels)

['Normal', 'High', 'Normal', 'High', 'Normal']