#### Homework
We are analyzing weekly transaction data for a small company.
The company wants to:

- Adjust revenues for tax
- Apply discount rules
- Classify customers
- Remove duplicate IDs
- Prepare data for structured analysis

##### Given:

In [1]:
revenues = [120, 250, 80, 310, 95]
tax_rate = 0.18
discount_rate = 0.10

##### 1.Compute revenues including tax.

In [2]:
revenues_with_tax = [r * (1 + tax_rate) for r in revenues]

print(revenues_with_tax)

[141.6, 295.0, 94.39999999999999, 365.79999999999995, 112.1]

##### 2. Compute final revenues after tax and discount.

In [3]:
final_revenues = [r * (1 + tax_rate) * (1 - discount_rate) for r in revenues]

print(final_revenues)

[127.44, 265.5, 84.96, 329.21999999999997, 100.89]

##### 3.Create a Boolean list indicating whether revenue > 100.

In [4]:
greater_than_100 = [r > 100 for r in revenues]

print(greater_than_100)

[True, True, False, True, False]

##### 4.Create a Boolean list indicating whether revenue is between 100 and 300.

In [5]:
between_100_300 = [100 < r < 300 for r in revenues]

print(between_100_300)

[True, True, False, False, False]

##### 5.Why do parentheses matter in the formula?


Parentheses control the order of operations in mathematical expressions.

In the revenue calculation we use:

Final Revenue = R * (1 + tax_rate) * (1 - discount_rate)

The parentheses ensure that the tax and discount adjustments are calculated first before multiplying the revenue.

Without parentheses, Python could apply operations in a different order, which would produce incorrect financial results.

#### Part 2
##### Using:

In [6]:
sales = [120, 250, 80, 310, 95]

##### 1.Compute total revenue manually using a loop.

In [7]:
total_revenue = 0

for s in sales:
    total_revenue = total_revenue + s

print(total_revenue)

855

##### 2.Compute average revenue.

In [8]:
average_revenue = total_revenue / len(sales)

print(average_revenue)

171.0

##### 3.Identify the maximum value without using max().

In [9]:
max_value = sales[0]

for s in sales:
    if s > max_value:
        max_value = s

print(max_value)

310

##### 4.Count how many values are greater than 150.

In [10]:
count = 0

for s in sales:
    if s > 150:
        count = count + 1

print(count)

2

##### 5.Create a new list of revenues after adding 5% commission.

In [11]:
commission_sales = [s * 1.05 for s in sales]

print(commission_sales)

[126.0, 262.5, 84.0, 325.5, 99.75]

#### Part 3.
- Segmentation rules:
- “Premium” if revenue > 250
- “Standard” if 100 < revenue ≤ 250
- “Low” otherwise

#### 1.Create a list of segment labels.

In [12]:
segments = []

for s in sales:
    if s > 250:
        segments.append("Premium")
    elif 100 < s <= 250:
        segments.append("Standard")
    else:
        segments.append("Low")

print(segments)

['Standard', 'Standard', 'Low', 'Premium', 'Low']

##### 2.Count how many customers fall into each segment.

In [13]:
premium_count = 0
standard_count = 0
low_count = 0

In [14]:
for seg in segments:
    if seg == "Premium":
        premium_count += 1
    elif seg == "Standard":
        standard_count += 1
    else:
        low_count += 1

print("Premium:", premium_count)
print("Standard:", standard_count)
print("Low:", low_count)

Premium: 1
Standard: 2
Low: 2

#### 3.Why does the order of elif statements matter?

The order of elif statements matters because Python evaluates conditions from top to bottom.

Once a condition is True, Python executes that block and skips the remaining conditions.

For example, if we check revenue > 100 before revenue > 250,
values greater than 250 would already match the first condition
and would never reach the Premium category.

#### Part 4
##### Given:

In [15]:
customer_ids = [1, 2, 3, 3, 4, 5, 5, 6]

##### 1.Remove duplicates using a set.

In [16]:
unique_ids = set(customer_ids)

print(unique_ids)

{1, 2, 3, 4, 5, 6}

##### 2.Convert back to a list.

In [17]:
unique_ids_list = list(unique_ids)

print(unique_ids_list)

[1, 2, 3, 4, 5, 6]

##### 3.Compare lengths before and after deduplication.

In [18]:
original_length = len(customer_ids)
unique_length = len(unique_ids_list)

print("Original length:", original_length)
print("Unique length:", unique_length)

Original length: 8
Unique length: 6

##### 4.Why sets are unordered.

Sets in Python are unordered collections because they are implemented using hash tables.

Elements in a set are stored based on their hash values rather than their insertion order. 
Because of this internal structure, Python does not guarantee any specific order when elements are stored or displayed.

This design allows sets to efficiently perform operations like removing duplicates and checking membership.

#### Part 5
##### Create a dictionary:

In [20]:
customer = {
    "name": "Anna",
    "revenue": 250,
    "city": "Yerevan"
}

##### 1.Add a new key "segment" based on revenue.

In [21]:
if customer["revenue"] > 250:
    customer["segment"] = "Premium"
elif 100 < customer["revenue"] <= 250:
    customer["segment"] = "Standard"
else:
    customer["segment"] = "Low"

print(customer)

{'name': 'Anna', 'revenue': 250, 'city': 'Yerevan', 'segment': 'Standard'}

##### 2.Update revenue to 300.

In [22]:
customer["revenue"] = 300

print(customer)

{'name': 'Anna', 'revenue': 300, 'city': 'Yerevan', 'segment': 'Standard'}

##### 3.Remove "city".

In [23]:
del customer["city"]

print(customer)

{'name': 'Anna', 'revenue': 300, 'segment': 'Standard'}

##### 4.Loop over the dictionary and print key-value pairs.

In [24]:
for key, value in customer.items():
    print(key, ":", value)

name : Anna
revenue : 300
segment : Standard

##### 5.Why are dictionaries useful for structured data?

Dictionaries are useful for structured data because they store information as key-value pairs.

Each key represents a specific attribute, while the value represents the data associated with that attribute.

This structure makes it easy to organize, access, and update data. For example, customer information such as name, revenue, and segment can be stored clearly in a dictionary.

Dictionaries are widely used in data analytics because they allow fast lookups and flexible data organization.

#### Part 6
##### Using:

In [26]:
revenues = [120, 250, 80, 310, 95]

##### 1.Create a list of revenues after 10% tax.

In [27]:
revenues_after_tax = [r * 0.9 for r in revenues]

print(revenues_after_tax)

[108.0, 225.0, 72.0, 279.0, 85.5]

##### 2.Create a list of revenues greater than 100.

In [28]:
greater_than_100 = [r for r in revenues if r > 100]

print(greater_than_100)

[120, 250, 310]

##### 3.Create a list labeling each revenue as:
- “High” if > 200
- “Normal” otherwise

In [29]:
labels = ["High" if r > 200 else "Normal" for r in revenues]

print(labels)

['Normal', 'High', 'Normal', 'High', 'Normal']

##### 4.Compare list comprehension vs loop in Markdown.

List comprehension is a concise way to create lists in Python. 
It allows us to perform operations, apply conditions, and generate new lists in a single readable line.

Using loops requires multiple lines of code where we initialize a list, iterate through elements, and append results manually.

List comprehension is often preferred in data analytics because it is more compact and usually easier to read when performing simple transformations or filtering operations.

However, traditional loops can be more flexible and easier to understand for complex logic.

#### Part 7
##### Convert our data into a DataFrame.

In [30]:
import pandas as pd

data = {
    "revenue": revenues
}

df = pd.DataFrame(data)
df

   revenue
0      120
1      250
2       80
3      310
4       95

##### 1.Add column "revenue_after_tax".

In [31]:
df["revenue_after_tax"] = df["revenue"] * 0.9

df

   revenue  revenue_after_tax
0      120              108.0
1      250              225.0
2       80               72.0
3      310              279.0
4       95               85.5

##### 2.Add column "segment" using conditional logic.

In [32]:
def segment_label(r):
    if r > 250:
        return "Premium"
    elif 100 < r <= 250:
        return "Standard"
    else:
        return "Low"

df["segment"] = df["revenue"].apply(segment_label)

df

   revenue  revenue_after_tax   segment
0      120              108.0  Standard
1      250              225.0  Standard
2       80               72.0       Low
3      310              279.0   Premium
4       95               85.5       Low

##### 3.Filter rows where revenue > 100.

In [33]:
filtered_df = df[df["revenue"] > 100]

filtered_df

   revenue  revenue_after_tax   segment
0      120              108.0  Standard
1      250              225.0  Standard
3      310              279.0   Premium

##### 4.Remove the "revenue_after_tax" column.

In [34]:
df = df.drop(columns=["revenue_after_tax"])

df

   revenue   segment
0      120  Standard
1      250  Standard
2       80       Low
3      310   Premium
4       95       Low

##### 5.Print the shape of the DataFrame.

In [35]:
print(df.shape)

(5, 2)

##### 6.Why is this easier than manual loops?

Using pandas DataFrames makes data analysis easier because operations can be applied to entire columns at once.

Instead of writing manual loops to process each value individually, pandas allows vectorized operations that are faster and require less code.

DataFrames also provide built-in tools for filtering, aggregation, and transformation, making data manipulation more efficient and easier to read.

### Bonus Reflection

**1. Difference between mutable and immutable objects**  
Mutable objects (like lists, dictionaries) can be changed in place, while immutable objects (like tuples, strings) cannot be modified after creation.

**2. Why loops are less efficient than pandas vectorization**  
Loops process data element by element, which is slow in Python. Pandas vectorization applies operations over entire columns at once, leveraging optimized C-level code for speed.

**3. How Boolean logic relates to SQL WHERE**  
Boolean logic (AND, OR, NOT) determines which rows meet conditions. In SQL, the `WHERE` clause filters rows using these logical expressions.

**4. Why understanding lists helps understand DataFrames**  
DataFrames are like tables of lists (columns). Knowing how lists store and manipulate data makes it easier to work with columns, apply operations, and understand indexing in DataFrames.