In [122]:
import pandas as pd

In [67]:
#Load the products CSV file into a DataFrame 
df_products = pd.read_csv('../data/raw/products.csv')

In [123]:
#Quick checks on the products DataFrame
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [4]:
df_products.info()

<class 'pandas.DataFrame'>
RangeIndex: 49693 entries, 0 to 49692
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     49693 non-null  int64
 1   product_name   49677 non-null  str
 2   aisle_id       49693 non-null  int64
 3   department_id  49693 non-null  int64
 4   prices         49693 non-null  float64
dtypes: float64(1), int64(3), str(1)
memory usage: 1.9 MB

In [44]:
df_products.shape[0]

49693

In [45]:
df_products.describe

<bound method NDFrame.describe of        product_id                                       product_name  \
0               1                         Chocolate Sandwich Cookies
1               2                                   All-Seasons Salt
2               3               Robust Golden Unsweetened Oolong Tea
3               4  Smart Ones Classic Favorites Mini Rigatoni Wit...
4               5                          Green Chile Anytime Sauce
...           ...                                                ...
49688       49684          Vodka, Triple Distilled, Twist of Vanilla
49689       49685                 En Croute Roast Hazelnut Cranberry
49690       49686                                   Artisan Baguette
49691       49687         Smartblend Healthy Metabolism Dry Cat Food
49692       49688                             Fresh Foaming Cleanser

       aisle_id  department_id  prices
0            61             19     5.8
1           104             13     9.3
2            94              7     4.5
3            38              1    10.5
4             5             13     4.3
...         ...            ...     ...
49688       124              5     5.3
49689        42              1     3.1
49690       112              3     7.8
49691        41              8     4.7
49692        73             11    13.5

[49693 rows x 5 columns]>

In [69]:
#Load the departments_t CSV file into a DataFrame 
df_departments_t = pd.read_csv('../data/processed/departments_t.csv')

In [ ]:
#Quick checks on the departments_t DataFrame
df_departments_t.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [48]:
df_departments_t.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   department_id  21 non-null     int64
 1   department     21 non-null     str
dtypes: int64(1), str(1)
memory usage: 468.0 bytes

In [49]:
df_departments_t.shape[0]

21

In [50]:
df_departments_t.describe

<bound method NDFrame.describe of     department_id       department
0               1           frozen
1               2            other
2               3           bakery
3               4          produce
4               5          alcohol
5               6    international
6               7        beverages
7               8             pets
8               9  dry goods pasta
9              10             bulk
10             11    personal care
11             12     meat seafood
12             13           pantry
13             14        breakfast
14             15     canned goods
15             16       dairy eggs
16             17        household
17             18           babies
18             19           snacks
19             20             deli
20             21          missing>

In [71]:
#Merge products with departments_t on 'department_id' using a left join
df_products_departments = pd.merge(
    df_products,
    df_departments_t,
    on = "department_id",
    how = "left",
    indicator = True
)
df_products_departments.head()

,product_id,product_name,aisle_id,department_id,prices,department,_merge
0,1,Chocolate Sandwich Cookies,61,19,5.8,snacks,both
1,2,All-Seasons Salt,104,13,9.3,pantry,both
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5,beverages,both
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5,frozen,both
4,5,Green Chile Anytime Sauce,5,13,4.3,pantry,both

In [72]:
#Looking at the indicator results
df_products_departments["_merge"].value_counts()

_merge
both          49693
left_only         0
right_only        0
Name: count, dtype: int64

In [77]:
#Investigating unmatched rows
df_products_departments[
    df_products_departments["_merge"] == "left_only"
].head()

Empty DataFrame
Columns: [product_id, product_name, aisle_id, department_id, prices, department, _merge]
Index: []

In [79]:
#cleaning the indicator results or rerun the merge without indicator=True
df_products_departments = pd.merge(
    df_products,
    df_departments_t,
    on = "department_id",
    how = "left"
)
df_products_departments.head()

,product_id,product_name,aisle_id,department_id,prices,department
0,1,Chocolate Sandwich Cookies,61,19,5.8,snacks
1,2,All-Seasons Salt,104,13,9.3,pantry
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5,frozen
4,5,Green Chile Anytime Sauce,5,13,4.3,pantry

#### Aisle

In [81]:
#Load the aisles CSV file into a DataFrame
df_aisles = pd.read_csv('../data/raw/aisles.csv')

In [82]:
#Quick checks on the aisles DataFrame
df_aisles.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [21]:
df_aisles.info

<bound method DataFrame.info of      aisle_id                       aisle
0           1       prepared soups salads
1           2           specialty cheeses
2           3         energy granola bars
3           4               instant foods
4           5  marinades meat preparation
..        ...                         ...
129       130    hot cereal pancake mixes
130       131                   dry pasta
131       132                      beauty
132       133  muscles joints pain relief
133       134  specialty wines champagnes

[134 rows x 2 columns]>

In [22]:
df_aisles.shape[0]

134

In [23]:
df_aisles.describe

<bound method NDFrame.describe of      aisle_id                       aisle
0           1       prepared soups salads
1           2           specialty cheeses
2           3         energy granola bars
3           4               instant foods
4           5  marinades meat preparation
..        ...                         ...
129       130    hot cereal pancake mixes
130       131                   dry pasta
131       132                      beauty
132       133  muscles joints pain relief
133       134  specialty wines champagnes

[134 rows x 2 columns]>

In [83]:
#Performing the second merge
df_products_enriched = pd.merge(
    df_products_departments,
    df_aisles,
    on="aisle_id",
    how="left"
)
df_products_enriched.head()

,product_id,product_name,aisle_id,department_id,prices,department,aisle
0,1,Chocolate Sandwich Cookies,61,19,5.8,snacks,cookies cakes
1,2,All-Seasons Salt,104,13,9.3,pantry,spices seasonings
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5,beverages,tea
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5,frozen,frozen meals
4,5,Green Chile Anytime Sauce,5,13,4.3,pantry,marinades meat preparation

In [85]:
#Checking the second merge with indicator True
df_products_aisles_check = pd.merge(
    df_products_departments,
    df_aisles,
    on="aisle_id",
    how="left",
    indicator=True
)

df_products_aisles_check["_merge"].value_counts()

_merge
both          49693
left_only         0
right_only        0
Name: count, dtype: int64

In [86]:
#Investigating unmuched aisle rows
df_products_aisles_check[
    df_products_aisles_check["_merge"] == "left_only"
].head()

Empty DataFrame
Columns: [product_id, product_name, aisle_id, department_id, prices, department, aisle, _merge]
Index: []

In [88]:
#cleaning the indicator results or rerun the merge without indicator=True
df_products_enriched = pd.merge(
    df_products_departments,
    df_aisles,
    on = "aisle_id",
    how = "left"
)
df_products_enriched.head()

,product_id,product_name,aisle_id,department_id,prices,department,aisle
0,1,Chocolate Sandwich Cookies,61,19,5.8,snacks,cookies cakes
1,2,All-Seasons Salt,104,13,9.3,pantry,spices seasonings
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5,beverages,tea
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5,frozen,frozen meals
4,5,Green Chile Anytime Sauce,5,13,4.3,pantry,marinades meat preparation

In [89]:
#Checking row counts
print(df_products.shape)
print(df_products_departments.shape)
print(df_products_enriched.shape)

(49693, 5)
(49693, 6)
(49693, 7)

In [92]:
#cheking uniquness in lookup tables before merging
df_departments_t["department_id"].is_unique

True

In [93]:
df_aisles["aisle_id"].is_unique

True

In [95]:
#Load the orders CSV file into a DataFrame
df_orders = pd.read_csv('../data/raw/orders.csv')

In [96]:
#Quick checks on the orders DataFra me
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [97]:
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int64
 1   user_id                 int64
 2   eval_set                str
 3   order_number            int64
 4   order_dow               int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
dtypes: float64(1), int64(5), str(1)
memory usage: 182.7 MB

In [98]:
df_orders.shape[0]

3421083

In [99]:
df_orders.describe

<bound method NDFrame.describe of          order_id  user_id eval_set  order_number  order_dow  \
0         2539329        1    prior             1          2
1         2398795        1    prior             2          3
2          473747        1    prior             3          3
3         2254736        1    prior             4          4
4          431534        1    prior             5          4
...           ...      ...      ...           ...        ...
3421078   2266710   206209    prior            10          5
3421079   1854736   206209    prior            11          4
3421080    626363   206209    prior            12          1
3421081   2977660   206209    prior            13          1
3421082    272231   206209    train            14          6

         order_hour_of_day  days_since_prior_order
0                        8                     NaN
1                        7                    15.0
2                       12                    21.0
3                        7                    29.0
4                       15                    28.0
...                    ...                     ...
3421078                 18                    29.0
3421079                 10                    30.0
3421080                 12                    18.0
3421081                 12                     7.0
3421082                 14                    30.0

[3421083 rows x 7 columns]>

In [100]:
# Filter orders to keep only the train dataset
df_oreders_train = df_orders [df_orders["eval_set"] == "train"]

In [101]:
#Load the order products train CSV file into a DataFrame
df_order_products_train = pd.read_csv ('../data/raw/order_products_train.csv')

In [102]:
#Quick checks on the order products train DataFrame
df_order_products_train.head()

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [103]:
df_order_products_train.info

<bound method DataFrame.info of          order_id  product_id  add_to_cart_order  reordered
0               1       49302                  1          1
1               1       11109                  2          1
2               1       10246                  3          0
3               1       49683                  4          0
4               1       43633                  5          1
...           ...         ...                ...        ...
1384612   3421063       14233                  3          1
1384613   3421063       35548                  4          1
1384614   3421070       35951                  1          1
1384615   3421070       16953                  2          1
1384616   3421070        4724                  3          1

[1384617 rows x 4 columns]>

In [105]:
df_order_products_train.shape[0]

1384617

In [106]:
df_order_products_train.describe

<bound method NDFrame.describe of          order_id  product_id  add_to_cart_order  reordered
0               1       49302                  1          1
1               1       11109                  2          1
2               1       10246                  3          0
3               1       49683                  4          0
4               1       43633                  5          1
...           ...         ...                ...        ...
1384612   3421063       14233                  3          1
1384613   3421063       35548                  4          1
1384614   3421070       35951                  1          1
1384615   3421070       16953                  2          1
1384616   3421070        4724                  3          1

[1384617 rows x 4 columns]>

In [107]:
#Performing the merge
#We merge the filtered order table with the transaction bridge table using order_id.
df_train_transaction = pd.merge(
    df_oreders_train,
    df_order_products_train,
    on = "order_id",
    how = "left",
)

df_train_transaction.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered
0,1187899,1,train,11,4,8,14.0,196,1,1
1,1187899,1,train,11,4,8,14.0,25133,2,1
2,1187899,1,train,11,4,8,14.0,38928,3,1
3,1187899,1,train,11,4,8,14.0,26405,4,1
4,1187899,1,train,11,4,8,14.0,39657,5,1

In [108]:
#Checking the merge with indicator= True
df_train_transaction_check = pd.merge(
    df_oreders_train,
    df_order_products_train,
    on = "order_id",
    how = "left",
    indicator = True
)
df_train_transaction_check.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge
0,1187899,1,train,11,4,8,14.0,196,1,1,both
1,1187899,1,train,11,4,8,14.0,25133,2,1,both
2,1187899,1,train,11,4,8,14.0,38928,3,1,both
3,1187899,1,train,11,4,8,14.0,26405,4,1,both
4,1187899,1,train,11,4,8,14.0,39657,5,1,both

In [109]:
#Inspecting the _merge column
df_train_transaction_check["_merge"].value_counts()

_merge
both          1384617
left_only           0
right_only          0
Name: count, dtype: int64

In [110]:
#Looking at unmuched orders
df_train_transaction_check[
    df_train_transaction_check["_merge"] == "left_only"
].head()

Empty DataFrame
Columns: [order_id, user_id, eval_set, order_number, order_dow, order_hour_of_day, days_since_prior_order, product_id, add_to_cart_order, reordered, _merge]
Index: []

In [111]:
#rerun without indicator= True
df_train_transaction_check = pd.merge(
    df_oreders_train,
    df_order_products_train,
    on = "order_id",
    how = "left"

)
df_train_transaction_check.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered
0,1187899,1,train,11,4,8,14.0,196,1,1
1,1187899,1,train,11,4,8,14.0,25133,2,1
2,1187899,1,train,11,4,8,14.0,38928,3,1
3,1187899,1,train,11,4,8,14.0,26405,4,1
4,1187899,1,train,11,4,8,14.0,39657,5,1

In [112]:
#Checking the row counts
print(df_oreders_train.shape)
print(df_order_products_train.shape)
print(df_train_transaction.shape)

(131209, 7)
(1384617, 4)
(1384617, 10)

In [113]:
#check all columns we have now
df_train_transaction.columns

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order', 'product_id',
       'add_to_cart_order', 'reordered'],
      dtype='str')

In [114]:
#The last step is to merge df_train_transactions with df_products_enriched.
df_train_analytic = pd.merge(
    df_train_transaction,
    df_products_enriched,
    on = "product_id",
    how = "left"
)
df_train_analytic.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,department,aisle
0,1187899,1,train,11,4,8,14.0,196,1,1,Soda,77.0,7.0,9.0,beverages,soft drinks
1,1187899,1,train,11,4,8,14.0,25133,2,1,Organic String Cheese,21.0,16.0,8.6,dairy eggs,packaged cheese
2,1187899,1,train,11,4,8,14.0,38928,3,1,0% Greek Strained Yogurt,120.0,16.0,12.6,dairy eggs,yogurt
3,1187899,1,train,11,4,8,14.0,26405,4,1,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,household,paper goods
4,1187899,1,train,11,4,8,14.0,39657,5,1,Milk Chocolate Almonds,45.0,19.0,6.8,snacks,candy chocolate

In [115]:
#Checking the final merge with indicator=True
df_train_analytic = pd.merge(
    df_train_analytic,
    df_products_enriched,
    on = "product_id",
    how = "left",
    indicator = True
)
df_train_analytic.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,prices_x,department_x,aisle_x,product_name_y,aisle_id_y,department_id_y,prices_y,department_y,aisle_y,_merge
0,1187899,1,train,11,4,8,14.0,196,1,1,...,9.0,beverages,soft drinks,Soda,77.0,7.0,9.0,beverages,soft drinks,both
1,1187899,1,train,11,4,8,14.0,25133,2,1,...,8.6,dairy eggs,packaged cheese,Organic String Cheese,21.0,16.0,8.6,dairy eggs,packaged cheese,both
2,1187899,1,train,11,4,8,14.0,38928,3,1,...,12.6,dairy eggs,yogurt,0% Greek Strained Yogurt,120.0,16.0,12.6,dairy eggs,yogurt,both
3,1187899,1,train,11,4,8,14.0,26405,4,1,...,1.0,household,paper goods,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,household,paper goods,both
4,1187899,1,train,11,4,8,14.0,39657,5,1,...,6.8,snacks,candy chocolate,Milk Chocolate Almonds,45.0,19.0,6.8,snacks,candy chocolate,both

In [ ]:
#Inspecting the _merge column
df_train_analytic["_merge"].value_counts()

_merge
both          1384796
left_only          88
right_only          0
Name: count, dtype: int64

In [119]:
#Investigating unmatched product rows
df_train_analytic[
    df_train_analytic["_merge"] == "left_only"
].head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,prices_x,department_x,aisle_x,product_name_y,aisle_id_y,department_id_y,prices_y,department_y,aisle_y,_merge
10784,3009052,1629,train,37,0,13,3.0,6799,24,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
52844,195363,7955,train,12,6,14,8.0,6799,4,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
59773,831974,9000,train,11,3,13,20.0,6799,19,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
64183,206208,9640,train,16,6,11,12.0,6799,6,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
81613,472316,12168,train,10,4,12,0.0,6799,12,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [121]:
#rerun without indicator=True
df_train_analytic = pd.merge(
    df_train_analytic,
    df_products_enriched,
    on = "product_id",
    how = "left"
)
df_train_analytic.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,prices_y,department_y,aisle_y,_merge,product_name,aisle_id,department_id,prices,department,aisle
0,1187899,1,train,11,4,8,14.0,196,1,1,...,9.0,beverages,soft drinks,both,Soda,77.0,7.0,9.0,beverages,soft drinks
1,1187899,1,train,11,4,8,14.0,25133,2,1,...,8.6,dairy eggs,packaged cheese,both,Organic String Cheese,21.0,16.0,8.6,dairy eggs,packaged cheese
2,1187899,1,train,11,4,8,14.0,38928,3,1,...,12.6,dairy eggs,yogurt,both,0% Greek Strained Yogurt,120.0,16.0,12.6,dairy eggs,yogurt
3,1187899,1,train,11,4,8,14.0,26405,4,1,...,1.0,household,paper goods,both,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,household,paper goods
4,1187899,1,train,11,4,8,14.0,39657,5,1,...,6.8,snacks,candy chocolate,both,Milk Chocolate Almonds,45.0,19.0,6.8,snacks,candy chocolate

In [120]:
df_train_analytic.columns

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order', 'product_id',
       'add_to_cart_order', 'reordered', 'product_name_x', 'aisle_id_x',
       'department_id_x', 'prices_x', 'department_x', 'aisle_x',
       'product_name_y', 'aisle_id_y', 'department_id_y', 'prices_y',
       'department_y', 'aisle_y', '_merge'],
      dtype='str')