#### Unzip files

In [4]:
import zipfile
with zipfile.ZipFile("../data/raw/Archive.zip", "r") as zip_ref:
    zip_ref.extractall("../data/raw")

#### Importing orders.csv file

In [5]:
import pandas as pd

df_orders = pd.read_csv('../data/raw/orders.csv')

print(df_orders.columns)
print(df_orders.shape)
df_orders.head()

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')
(3421083, 7)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

#### Importing order_products_train .csv file

In [6]:
# Reading data
df_orders_products_train = pd.read_csv('../data/raw/order_products_train.csv')
print(df_orders_products_train.columns)
print(df_orders_products_train.shape)
df_orders_products_train.head()

Index(['order_id', 'product_id', 'add_to_cart_order', 'reordered'], dtype='str')
(1384617, 4)

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

#### Importing products.csv file

In [7]:
df_products = pd.read_csv("../data/raw/products.csv")
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

#### Importing departments_t.csv

In [8]:
df_departments = pd.read_csv('../data/processed/departments_t.csv')
print(df_departments.columns)
print(df_departments.shape)
df_departments.head()

Index(['department_id', 'department'], dtype='str')
(21, 2)

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

#### Importing aisles.csv

In [9]:
df_aisles = pd.read_csv('../data/raw/aisles.csv')
print(df_aisles.columns)
print(df_aisles.shape)
df_aisles.head()

Index(['aisle_id', 'aisle'], dtype='str')
(134, 2)

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

#### The orders Table

In [10]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [ ]:
#How many total orders are there?
df_orders.shape

(3421083, 7)

In [ ]:
#How many users are represented?
df_orders["user_id"].nunique()

206209

In [23]:
#What is the distribution of eval_set?
df_orders["eval_set"].value_counts()

eval_set
prior    3214874
train     131209
test       75000
Name: count, dtype: int64

In [24]:
#On which days do customers place orders most frequently?
df_orders["order_dow"].value_counts()

order_dow
0    600905
1    587478
2    467260
5    453368
6    448761
3    436972
4    426339
Name: count, dtype: int64

In [25]:
#At what hours do customers place orders most frequently?
df_orders["order_hour_of_day"].value_counts()

order_hour_of_day
10    288418
11    284728
15    283639
14    283042
13    277999
12    272841
16    272553
9     257812
17    228795
18    182912
8     178201
19    140569
20    104292
7      91868
21     78109
22     61468
23     40043
6      30529
0      22758
1      12398
5       9569
2       7539
4       5527
3       5474
Name: count, dtype: int64

In [26]:
#Are missing values in days_since_prior_order meaningful?
df_orders["days_since_prior_order"].isna().sum()

np.int64(206209)

In [12]:
## Consistancy Check: Order ID
if df_orders["order_id"].nunique() == df_orders.shape[0]:
    print('Happy')
else:
    print('Sad')

Happy

In [14]:
df_dow =  df_orders['order_dow'].value_counts().reset_index()

In [15]:
df_dow.sort_values('order_dow')

   order_dow   count
0          0  600905
1          1  587478
2          2  467260
5          3  436972
6          4  426339
3          5  453368
4          6  448761

In [16]:
df_dow.to_csv('../data/processed/dow.csv', index=False)

In [17]:
df_ohod = df_orders['order_hour_of_day'].value_counts().reset_index().sort_values('order_hour_of_day')
df_ohod.head()

    order_hour_of_day  count
18                  0  22758
19                  1  12398
21                  2   7539
23                  3   5474
22                  4   5527

In [18]:
df_ohod.to_csv('../data/processed/ohod.csv')

In [19]:
df_ohod.to_excel('../data/processed/ohod.xlsx', index = False)

In [20]:
df_orders.loc[df_orders["order_number"] == 1, "days_since_prior_order"].isna().all()

np.True_

In [21]:
df_orders

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
...,...,...,...,...,...,...,...
3421078,2266710,206209,prior,10,5,18,29.0
3421079,1854736,206209,prior,11,4,10,30.0
3421080,626363,206209,prior,12,1,12,18.0
3421081,2977660,206209,prior,13,1,12,7.0
3421082,272231,206209,train,14,6,14,30.0

#### The order_products_train Table

In [28]:
#How many line items are there?
len(df_orders_products_train)

1384617

In [30]:
#How many unique orders are represented?
df_orders_products_train["order_id"].nunique()

131209

In [31]:
#How many unique products are represented?
df_orders_products_train["product_id"].nunique()

39123

In [33]:
#What proportion of items are reordered?
df_orders_products_train["reordered"].mean()

np.float64(0.5985944127509629)

In [35]:
#What does the distribution of add_to_cart_order look like?
df_orders_products_train["add_to_cart_order"].describe()

count    1.384617e+06
mean     8.758044e+00
std      7.423936e+00
min      1.000000e+00
25%      3.000000e+00
50%      7.000000e+00
75%      1.200000e+01
max      8.000000e+01
Name: add_to_cart_order, dtype: float64

#### The products Table

In [37]:
#How many products exist?
df_products.shape

(49693, 5)

In [46]:
#Are product IDs unique?
df_products["product_id"].is_unique

True

In [ ]:
#Ստուգել բոլոր կրկնվող product_id-ները։
df_products[df_products["product_id"].duplicated()]

Empty DataFrame
Columns: [product_id, product_name, aisle_id, department_id, prices]
Index: []

In [ ]:
#Քանի duplicate կա
df_products["product_id"].duplicated().sum()

np.int64(7)

In [ ]:
#Եթե դրանք նույնական տողեր են, կարող եմ մաքրել
df_products = df_products.drop_duplicates(subset="product_id")

In [47]:
#How many departments are represented in the product catalog?
df_products["department_id"].nunique()

21

In [48]:
#How many aisles are represented in the product catalog?
df_products["aisle_id"].nunique()

134

In [49]:
#Do some product names repeat?
df_products["product_name"].duplicated().sum()

np.int64(15)

#### The departments_t Table

In [50]:
#How many departments exist?
df_departments.shape[0]

21

In [51]:
#Are department IDs unique?
df_departments["department_id"].is_unique

True

#### The aisles Table

In [53]:
#How many aisles exist?
df_aisles.shape[0]

134

In [56]:
#Are aisle IDs unique?
df_aisles["aisle_id"].is_unique

True

#### Exploring the orders Table

In [57]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [59]:
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int64
 1   user_id                 int64
 2   eval_set                str
 3   order_number            int64
 4   order_dow               int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
dtypes: float64(1), int64(5), str(1)
memory usage: 182.7 MB

In [62]:
df_orders.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,"3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,214,874.00"
mean,"1,710,542.00","102,978.21",17.15,2.78,13.45,11.11
std,"987,581.74","59,533.72",17.73,2.05,4.23,9.21
min,1.00,1.00,1.00,0.00,0.00,0.00
25%,"855,271.50","51,394.00",5.00,1.00,10.00,4.00
50%,"1,710,542.00","102,689.00",11.00,3.00,13.00,7.00
75%,"2,565,812.50","154,385.00",23.00,5.00,16.00,15.00
max,"3,421,083.00","206,209.00",100.00,6.00,23.00,30.00

In [ ]:
#փոխեցինք float format-ը
pd.options.display.float_format = '{:,.2f}'.format

In [ ]:
#missing values
df_orders.isna().sum()

order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

#### Analytical questions that can be answered from orders

In [ ]:
#Q1: How many unique orders exist?
df_orders["order_id"].nunique()

3421083

In [65]:
#Q2: How many distinct customers are represented in the dataset?
df_orders["user_id"].nunique()

206209

In [66]:
#Q3: Exploring the eval_set distribution
df_orders["eval_set"].value_counts(dropna=False)

eval_set
prior    3214874
train     131209
test       75000
Name: count, dtype: int64

In [67]:
#Q4: Orders by day of week
df_orders["order_dow"].value_counts().sort_index()

order_dow
0    600905
1    587478
2    467260
3    436972
4    426339
5    453368
6    448761
Name: count, dtype: int64

In [69]:
#Q5: Orders by hour of day
df_orders["order_hour_of_day"].value_counts().sort_index()

order_hour_of_day
0      22758
1      12398
2       7539
3       5474
4       5527
5       9569
6      30529
7      91868
8     178201
9     257812
10    288418
11    284728
12    272841
13    277999
14    283042
15    283639
16    272553
17    228795
18    182912
19    140569
20    104292
21     78109
22     61468
23     40043
Name: count, dtype: int64

In [70]:
#Q5:Understanding missing values in days_since_prior_order
df_orders["days_since_prior_order"].isna().sum()

np.int64(206209)

In [72]:
#Logical check: first orders and null values
df_orders.loc[df_orders["order_number"] == 1, "days_since_prior_order"].isna().all()

np.True_

#### Consistency checks for the orders table

In [73]:
#Is order_id unique?
df_orders["order_id"].is_unique

True

In [74]:
#Is order_dow in the correct range?
df_orders["order_dow"].between(0, 6).all()

np.True_

In [75]:
#Is order_hour_of_day in the correct range?
df_orders["order_hour_of_day"].between(0, 23).all()

np.True_

#### Filtering the orders table to train orders

In [76]:
df_orders_train = df_orders[df_orders["eval_set"] == "train"]
df_orders_train.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,train,11,4,8,14.00
25,1492625,2,train,15,1,11,30.00
49,2196797,5,train,5,0,11,6.00
74,525192,7,train,21,2,11,6.00
78,880375,8,train,4,1,14,10.00

In [77]:
#Keeping only the columns we need
df_orders_train.drop(columns=["eval_set"])
df_orders_train.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,train,11,4,8,14.00
25,1492625,2,train,15,1,11,30.00
49,2196797,5,train,5,0,11,6.00
74,525192,7,train,21,2,11,6.00
78,880375,8,train,4,1,14,10.00

In [78]:
del df_orders

##### Exploring the order_products_train Table

In [79]:
#Previewing the data
df_orders_products_train.head()

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [80]:
#Inspecting the schema
df_orders_products_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 1384617 entries, 0 to 1384616
Data columns (total 4 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   order_id           1384617 non-null  int64
 1   product_id         1384617 non-null  int64
 2   add_to_cart_order  1384617 non-null  int64
 3   reordered          1384617 non-null  int64
dtypes: int64(4)
memory usage: 42.3 MB

In [81]:
#Looking at data types
df_orders_products_train.dtypes

order_id             int64
product_id           int64
add_to_cart_order    int64
reordered            int64
dtype: object

In [82]:
#Descriptive statistics
df_orders_products_train.describe()

          order_id   product_id  add_to_cart_order    reordered
count 1,384,617.00 1,384,617.00       1,384,617.00 1,384,617.00
mean  1,706,297.62    25,556.24               8.76         0.60
std     989,732.65    14,121.27               7.42         0.49
min           1.00         1.00               1.00         0.00
25%     843,370.00    13,380.00               3.00         0.00
50%   1,701,880.00    25,298.00               7.00         1.00
75%   2,568,023.00    37,940.00              12.00         1.00
max   3,421,070.00    49,688.00              80.00         1.00

In [83]:
#Missing values
df_orders_products_train.isna().sum()

order_id             0
product_id           0
add_to_cart_order    0
reordered            0
dtype: int64

In [84]:
#Q1: How many line items exist?
len(df_orders_products_train)

1384617

In [85]:
#Q2: How many unique orders are represented in this table?
df_orders_products_train["order_id"].nunique()

131209

In [86]:
#Q3: How many unique products are represented in this table?
df_orders_products_train["product_id"].nunique()

39123

In [87]:
#Q4: Exploring reorder behavior
df_orders_products_train["reordered"].value_counts(dropna=False)

reordered
1    828824
0    555793
Name: count, dtype: int64

In [88]:
#Q5: Reorder share
df_orders_products_train["reordered"].value_counts(normalize=False)

reordered
1    828824
0    555793
Name: count, dtype: int64

In [89]:
df_orders_products_train["reordered"].value_counts(normalize=True)

reordered
1   0.60
0   0.40
Name: proportion, dtype: float64

In [90]:
#Q6: Understanding add_to_cart_order
df_orders_products_train["add_to_cart_order"].describe()

count   1,384,617.00
mean            8.76
std             7.42
min             1.00
25%             3.00
50%             7.00
75%            12.00
max            80.00
Name: add_to_cart_order, dtype: float64

In [91]:
#Q7: Which cart positions appear most often?
df_orders_products_train["add_to_cart_order"].value_counts().sort_index().head(20)

add_to_cart_order
1     131209
2     124364
3     116996
4     108963
5     100745
6      91850
7      83142
8      74601
9      66618
10     59401
11     52848
12     46814
13     41431
14     36588
15     32194
16     28363
17     24841
18     21733
19     19014
20     16541
Name: count, dtype: int64

In [92]:
#Understanding repeated keys in the table
df_orders_products_train["order_id"].is_unique

False

In [93]:
df_orders_products_train["product_id"].is_unique

False

#### Consistency checks for the order_products_train table

In [95]:
#Is reordered limited to valid values?
df_orders_products_train["reordered"].isin([0, 1]).all()

np.True_

In [96]:
#Is add_to_cart_order positive?
(df_orders_products_train["add_to_cart_order"] > 0).all()

np.True_

In [97]:
#Are there missing values in the key columns?
df_orders_products_train[["order_id", "product_id"]].isna().sum()

order_id      0
product_id    0
dtype: int64

#### Exploring the products Table

In [98]:
#Previewing the data
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.80
1,2,All-Seasons Salt,104,13,9.30
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50
4,5,Green Chile Anytime Sauce,5,13,4.30

In [99]:
#Inspecting the schema
df_products.info()

<class 'pandas.DataFrame'>
Index: 49686 entries, 0 to 49692
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     49686 non-null  int64
 1   product_name   49670 non-null  str
 2   aisle_id       49686 non-null  int64
 3   department_id  49686 non-null  int64
 4   prices         49686 non-null  float64
dtypes: float64(1), int64(3), str(1)
memory usage: 2.3 MB

In [100]:
#Looking at data types
df_products.dtypes

product_id         int64
product_name         str
aisle_id           int64
department_id      int64
prices           float64
dtype: object

In [101]:
#Descriptive statistics
df_products.describe()

       product_id  aisle_id  department_id    prices
count   49,686.00 49,686.00      49,686.00 49,686.00
mean    24,844.83     67.77          11.73      9.99
std     14,343.89     38.32           5.85    453.55
min          1.00      1.00           1.00      1.00
25%     12,423.25     35.00           7.00      4.10
50%     24,844.50     69.00          13.00      7.10
75%     37,266.75    100.00          17.00     11.20
max     49,688.00    134.00          21.00 99,999.00

In [102]:
#Missing values
df_products.isna().sum()

product_id        0
product_name     16
aisle_id          0
department_id     0
prices            0
dtype: int64

In [103]:
#Q1: How many unique products exist?
df_products["product_id"].nunique()

49686

In [104]:
#Q2: Are product IDs unique?
df_products["product_id"].is_unique

True

In [105]:
#Q3: How many unique departments are referenced in the product table?
df_products["department_id"].nunique()

21

In [106]:
#Q4: How many unique aisles are referenced in the product table?
df_products["aisle_id"].nunique()

134

In [107]:
#Q5: Do some product names repeat?
df_products["product_name"].duplicated().sum()

np.int64(15)

#### Consistency checks for the products table

In [108]:
#Are product_id values unique?
df_products["product_id"].is_unique

True

In [109]:
#Are department_id values missing?
df_products["department_id"].isna().sum()

np.int64(0)

In [110]:
#Are aisle_id values missing?
df_products["aisle_id"].isna().sum()

np.int64(0)

#### Exploring the departments_t Table

In [111]:
#Previewing the data
df_departments.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [112]:
#Inspecting the schema
df_departments.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   department_id  21 non-null     int64
 1   department     21 non-null     str
dtypes: int64(1), str(1)
memory usage: 468.0 bytes

In [113]:
#Looking at data types
df_departments.dtypes

department_id    int64
department         str
dtype: object

In [114]:
#Missing values
df_departments.isna().sum()

department_id    0
department       0
dtype: int64

##### Analytical questions that can be answered from departments_t

In [115]:
#Q1: How many departments exist?
df_departments["department"].nunique()

21

In [116]:
#Q2: Are department_id values unique?
df_departments["department_id"].is_unique

True

In [117]:
#Q3: Are there missing values in the table?
df_departments.isna().sum()

department_id    0
department       0
dtype: int64

#### Exploring the aisles Table

In [118]:
#Previewing the data
df_aisles.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [119]:
#Inspecting the schema
df_aisles.info()

<class 'pandas.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   aisle_id  134 non-null    int64
 1   aisle     134 non-null    str
dtypes: int64(1), str(1)
memory usage: 2.2 KB

In [120]:
#Looking at data types
df_aisles.dtypes

aisle_id    int64
aisle         str
dtype: object

In [121]:
#Missing values
df_aisles.isna().sum()

aisle_id    0
aisle       0
dtype: int64

#### Analytical questions that can be answered from aisles

In [122]:
#Q1: How many aisles exist?
df_aisles["aisle"].nunique()

134

In [123]:
#Q2: Are aisle_id values unique?
df_aisles["aisle_id"].is_unique

True

In [124]:
#Q3: Are there missing values in the table?
df_aisles.isna().sum()

aisle_id    0
aisle       0
dtype: int64

#### Merge

In [126]:
#Performing the merge
df_products_departments = pd.merge(
    df_products,
    df_departments,
    on="department_id",
    how="left"
)

df_products_departments.head()

,product_id,product_name,aisle_id,department_id,prices,department
0,1,Chocolate Sandwich Cookies,61,19,5.80,snacks
1,2,All-Seasons Salt,104,13,9.30,pantry
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen
4,5,Green Chile Anytime Sauce,5,13,4.30,pantry

In [127]:
#Understanding the indicator Argument
df_products_departments_check = pd.merge(
    df_products,
    df_departments,
    on="department_id",
    how="left",
    indicator=True
)

df_products_departments_check.head()

,product_id,product_name,aisle_id,department_id,prices,department,_merge
0,1,Chocolate Sandwich Cookies,61,19,5.80,snacks,both
1,2,All-Seasons Salt,104,13,9.30,pantry,both
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,beverages,both
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen,both
4,5,Green Chile Anytime Sauce,5,13,4.30,pantry,both

In [128]:
#Looking at the indicator results
df_products_departments_check["_merge"].value_counts()

_merge
both          49686
left_only         0
right_only        0
Name: count, dtype: int64

In [129]:
#Investigating unmatched rows
df_products_departments_check[
    df_products_departments_check["_merge"] == "left_only"
].head()

Empty DataFrame
Columns: [product_id, product_name, aisle_id, department_id, prices, department, _merge]
Index: []

In [130]:
#Cleaning the indicator result
df_products_departments = pd.merge(
    df_products,
    df_departments,
    on="department_id",
    how="left"
)

df_products_departments.head()

,product_id,product_name,aisle_id,department_id,prices,department
0,1,Chocolate Sandwich Cookies,61,19,5.80,snacks
1,2,All-Seasons Salt,104,13,9.30,pantry
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen
4,5,Green Chile Anytime Sauce,5,13,4.30,pantry

In [ ]:
#Download new files
import pandas as pd
df = pd.read_csv(f'https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/raw/customers.csv'{i})
df.to_csv()= 'https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/processed/states.csv'

In [138]:
df_customers = pd.read_csv(URL_CUSTOMERS)

df_customers.shape

(206209, 10)

In [140]:
df_customers.head()

,user_id,First Name,Surnam,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

In [141]:
URLS = {
    'customers.csv': URL_CUSTOMERS,
    'state.csv': URL_STATES}

In [144]:
for i in URLS:
    print(f'Downloading {i}[0]')
    df = pd.read_csv(i[1])
    df.to_csv(f'../data/downloads/{i}[0]')
    print(f'saving {i} in ../data/downloads')

print('The job is donw')

Downloading customers.csv[0]

FileNotFoundError: [Errno 2] No such file or directory: 'u'