In [1]:
# Import pandas library for data manipulation
import pandas as pd

In [2]:
# Define URLs of the datasets that need to be downloaded
URLS = [
    "https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/raw/customers.csv",
    "https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/raw/states.csv"
]

In [3]:
# Define filenames for saving the datasets locally
names = ["customers", "states"]

In [4]:
# Download customers dataset from URL
df_customers = pd.read_csv(
"https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/raw/customers.csv"
)

# Save customers dataset into raw folder
df_customers.to_csv("../data/raw/customers.csv", index=False)

In [5]:
# Download states dataset from URL
df_states = pd.read_csv(
"https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/raw/states.csv"
)

# Save states dataset into raw folder
df_states.to_csv("../data/raw/states.csv", index=False)

In [6]:
# Check first rows of datasets
df_customers.head()

,user_id,First Name,Surnam,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

In [7]:
df_states.head()

           state     region     division
0    Connecticut  Northeast  New England
1          Maine  Northeast  New England
2  Massachusetts  Northeast  New England
3  New Hampshire  Northeast  New England
4   Rhode Island  Northeast  New England

In [8]:
# Load datasets from raw folder

df_orders = pd.read_csv("../data/raw/orders.csv")
df_customers = pd.read_csv("../data/raw/customers.csv")
df_states = pd.read_csv("../data/raw/states.csv")

In [9]:
# Check first rows of orders dataset
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [10]:
df_orders.columns

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')

In [11]:
df_customers.columns

Index(['user_id', 'First Name', 'Surnam', 'Gender', 'STATE', 'Age',
       'date_joined', 'n_dependants', 'fam_status', 'income'],
      dtype='str')

In [12]:
df_states.columns

Index(['state', 'region', 'division'], dtype='str')

In [14]:
# Merge orders dataset with customers dataset using user_id
df = df_orders.merge(df_customers, on="user_id", how="left")

In [15]:
# Check first rows of merged dataset
df.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,First Name,Surnam,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,2539329,1,prior,1,2,8,NaN,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
1,2398795,1,prior,2,3,7,15.0,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
2,473747,1,prior,3,3,12,21.0,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
3,2254736,1,prior,4,4,7,29.0,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423
4,431534,1,prior,5,4,15,28.0,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423

In [16]:
# Check dataset shape
df.shape

(3421083, 16)

In [17]:
# Rename 'STATE' column to 'state' to match states dataset
df = df.rename(columns={"STATE": "state"})

In [18]:
# Merge the dataframe with states dataset on 'state'
df = df.merge(df_states, on="state", how="left")

In [19]:
# Check first rows
df.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,First Name,Surnam,Gender,state,Age,date_joined,n_dependants,fam_status,income,region,division
0,2539329,1,prior,1,2,8,NaN,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
1,2398795,1,prior,2,3,7,15.0,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
2,473747,1,prior,3,3,12,21.0,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
3,2254736,1,prior,4,4,7,29.0,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
4,431534,1,prior,5,4,15,28.0,Linda,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central

In [20]:
# Check dataframe shape
df.shape

(3421083, 18)

In [22]:
#Save final merged dataset into processed folder
df.to_csv("../data/processed/orders_customers_states.csv", index=False)

In [ ]:
#Missing values
df.isna().sum()

order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
First Name                188567
Surnam                         0
Gender                         0
state                          0
Age                            0
date_joined                    0
n_dependants                   0
fam_status                     0
income                         0
region                         0
division                       0
dtype: int64

In [26]:
#Duplicates
df.duplicated().sum()

np.int64(0)

In [27]:
#Statistics
df.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,Age,n_dependants,income
count,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.214874e+06,3.421083e+06,3.421083e+06,3.421083e+06
mean,1.710542e+06,1.029782e+05,1.715486e+01,2.776219e+00,1.345202e+01,1.111484e+01,4.952564e+01,1.500950e+00,9.665578e+04
std,9.875817e+05,5.953372e+04,1.773316e+01,2.046829e+00,4.226088e+00,9.206737e+00,1.848321e+01,1.119455e+00,4.327100e+04
min,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.800000e+01,0.000000e+00,2.590300e+04
25%,8.552715e+05,5.139400e+04,5.000000e+00,1.000000e+00,1.000000e+01,4.000000e+00,3.400000e+01,0.000000e+00,6.299800e+04
50%,1.710542e+06,1.026890e+05,1.100000e+01,3.000000e+00,1.300000e+01,7.000000e+00,4.900000e+01,2.000000e+00,9.475800e+04
75%,2.565812e+06,1.543850e+05,2.300000e+01,5.000000e+00,1.600000e+01,1.500000e+01,6.600000e+01,3.000000e+00,1.257450e+05
max,3.421083e+06,2.062090e+05,1.000000e+02,6.000000e+00,2.300000e+01,3.000000e+01,8.100000e+01,3.000000e+00,5.939010e+05

In [29]:
#unique users / states
df["user_id"].nunique()
df["state"].nunique()

51