In [4]:
import pandas as pd

#### Unzip files

In [5]:
import zipfile
with zipfile.ZipFile("../data/raw/Archive.zip", "r") as zip_ref:
    zip_ref.extractall("../data/raw")

#### Importing orders.csv file

In [6]:
df_orders = pd.read_csv('../data/raw/orders.csv')

print(df_orders.columns)
print(df_orders.shape)
df_orders.head()

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')
(3421083, 7)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

#### Importing order_products_train .csv file

In [7]:
# Reading data
df_orders_products_train = pd.read_csv('../data/raw/order_products_train.csv')
print(df_orders_products_train.columns)
print(df_orders_products_train.shape)
df_orders_products_train.head()

Index(['order_id', 'product_id', 'add_to_cart_order', 'reordered'], dtype='str')
(1384617, 4)

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

#### Importing products.csv file

In [8]:
df_products = pd.read_csv("../data/raw/products.csv")
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

#### Importing departments_t.csv

In [9]:
df_departments = pd.read_csv('../data/processed/departments_t.csv')
print(df_departments.columns)
print(df_departments.shape)
df_departments.head()

Index(['department_id', 'department'], dtype='str')
(21, 2)

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

#### Importing aisles.csv

In [10]:
df_aisles = pd.read_csv('../data/raw/aisles.csv')
print(df_aisles.columns)
print(df_aisles.shape)
df_aisles.head()

Index(['aisle_id', 'aisle'], dtype='str')
(134, 2)

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

#### The orders Table

In [11]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [12]:
#How many total orders are there?
df_orders.shape

(3421083, 7)

In [13]:
#How many users are represented?
df_orders["user_id"].nunique()

206209

In [14]:
#What is the distribution of eval_set?
df_orders["eval_set"].value_counts()

eval_set
prior    3214874
train     131209
test       75000
Name: count, dtype: int64

In [15]:
#On which days do customers place orders most frequently?
df_orders["order_dow"].value_counts()

order_dow
0    600905
1    587478
2    467260
5    453368
6    448761
3    436972
4    426339
Name: count, dtype: int64

In [16]:
#At what hours do customers place orders most frequently?
df_orders["order_hour_of_day"].value_counts()

order_hour_of_day
10    288418
11    284728
15    283639
14    283042
13    277999
12    272841
16    272553
9     257812
17    228795
18    182912
8     178201
19    140569
20    104292
7      91868
21     78109
22     61468
23     40043
6      30529
0      22758
1      12398
5       9569
2       7539
4       5527
3       5474
Name: count, dtype: int64

In [17]:
#Are missing values in days_since_prior_order meaningful?
df_orders["days_since_prior_order"].isna().sum()

np.int64(206209)

In [18]:
## Consistancy Check: Order ID
if df_orders["order_id"].nunique() == df_orders.shape[0]:
    print('Happy')
else:
    print('Sad')

Happy

In [19]:
df_dow =  df_orders['order_dow'].value_counts().reset_index()

In [20]:
df_dow.sort_values('order_dow')

   order_dow   count
0          0  600905
1          1  587478
2          2  467260
5          3  436972
6          4  426339
3          5  453368
4          6  448761

In [21]:
df_dow.to_csv('../data/processed/dow.csv', index=False)

In [22]:
df_ohod = df_orders['order_hour_of_day'].value_counts().reset_index().sort_values('order_hour_of_day')
df_ohod.head()

    order_hour_of_day  count
18                  0  22758
19                  1  12398
21                  2   7539
23                  3   5474
22                  4   5527

In [23]:
df_ohod.to_csv('../data/processed/ohod.csv')

In [24]:
df_ohod.to_excel('../data/processed/ohod.xlsx', index = False)

In [25]:
df_orders.loc[df_orders["order_number"] == 1, "days_since_prior_order"].isna().all()

np.True_

In [26]:
df_orders

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
...,...,...,...,...,...,...,...
3421078,2266710,206209,prior,10,5,18,29.0
3421079,1854736,206209,prior,11,4,10,30.0
3421080,626363,206209,prior,12,1,12,18.0
3421081,2977660,206209,prior,13,1,12,7.0
3421082,272231,206209,train,14,6,14,30.0

#### The order_products_train Table

In [27]:
#How many line items are there?
len(df_orders_products_train)

1384617

In [28]:
#How many unique orders are represented?
df_orders_products_train["order_id"].nunique()

131209

In [29]:
#How many unique products are represented?
df_orders_products_train["product_id"].nunique()

39123

In [30]:
#What proportion of items are reordered?
df_orders_products_train["reordered"].mean()

np.float64(0.5985944127509629)

In [31]:
#What does the distribution of add_to_cart_order look like?
df_orders_products_train["add_to_cart_order"].describe()

count    1.384617e+06
mean     8.758044e+00
std      7.423936e+00
min      1.000000e+00
25%      3.000000e+00
50%      7.000000e+00
75%      1.200000e+01
max      8.000000e+01
Name: add_to_cart_order, dtype: float64

#### The products Table

In [32]:
#How many products exist?
df_products.shape

(49693, 5)

In [33]:
#Are product IDs unique?
df_products["product_id"].is_unique

False

In [34]:
#Ստուգել բոլոր կրկնվող product_id-ները։
df_products[df_products["product_id"].duplicated()]

,product_id,product_name,aisle_id,department_id,prices
462,462,Fiber 4g Gummy Dietary Supplement,70,11,4.8
6800,6800,Sprouted Quinoa Flakes Baby Cereal,92,18,14.0
18459,18458,Ranger IPA,27,5,9.2
26521,26520,Cheese Shredded Sharp Cheddar Reduced Fat 2%,21,16,2.9
26810,26808,Black House Coffee Roasty Stout Beer,27,5,13.4
35309,35306,Gluten Free Organic Peanut Butter & Chocolate ...,121,14,6.8
35495,35491,Adore Forever Body Wash,127,11,9.9

In [35]:
#Քանի duplicate կա
df_products["product_id"].duplicated().sum()

np.int64(7)

In [36]:
#Եթե դրանք նույնական տողեր են, կարող եմ մաքրել
df_products = df_products.drop_duplicates(subset="product_id")

In [37]:
#How many departments are represented in the product catalog?
df_products["department_id"].nunique()

21

In [38]:
#How many aisles are represented in the product catalog?
df_products["aisle_id"].nunique()

134

In [39]:
#Do some product names repeat?
df_products["product_name"].duplicated().sum()

np.int64(15)

#### The departments_t Table

In [40]:
#How many departments exist?
df_departments.shape[0]

21

In [41]:
#Are department IDs unique?
df_departments["department_id"].is_unique

True

#### The aisles Table

In [42]:
#How many aisles exist?
df_aisles.shape[0]

134

In [43]:
#Are aisle IDs unique?
df_aisles["aisle_id"].is_unique

True

#### Exploring the orders Table

In [44]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [45]:
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int64
 1   user_id                 int64
 2   eval_set                str
 3   order_number            int64
 4   order_dow               int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
dtypes: float64(1), int64(5), str(1)
memory usage: 182.7 MB

In [46]:
df_orders.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.214874e+06
mean,1.710542e+06,1.029782e+05,1.715486e+01,2.776219e+00,1.345202e+01,1.111484e+01
std,9.875817e+05,5.953372e+04,1.773316e+01,2.046829e+00,4.226088e+00,9.206737e+00
min,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.552715e+05,5.139400e+04,5.000000e+00,1.000000e+00,1.000000e+01,4.000000e+00
50%,1.710542e+06,1.026890e+05,1.100000e+01,3.000000e+00,1.300000e+01,7.000000e+00
75%,2.565812e+06,1.543850e+05,2.300000e+01,5.000000e+00,1.600000e+01,1.500000e+01
max,3.421083e+06,2.062090e+05,1.000000e+02,6.000000e+00,2.300000e+01,3.000000e+01

In [47]:
#փոխեցինք float format-ը
pd.options.display.float_format = '{:,.2f}'.format

In [48]:
#missing values
df_orders.isna().sum()

order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

#### Analytical questions that can be answered from orders

In [49]:
#Q1: How many unique orders exist?
df_orders["order_id"].nunique()

3421083

In [50]:
#Q2: How many distinct customers are represented in the dataset?
df_orders["user_id"].nunique()

206209

In [51]:
#Q3: Exploring the eval_set distribution
df_orders["eval_set"].value_counts(dropna=False)

eval_set
prior    3214874
train     131209
test       75000
Name: count, dtype: int64

In [52]:
#Q4: Orders by day of week
df_orders["order_dow"].value_counts().sort_index()

order_dow
0    600905
1    587478
2    467260
3    436972
4    426339
5    453368
6    448761
Name: count, dtype: int64

In [53]:
#Q5: Orders by hour of day
df_orders["order_hour_of_day"].value_counts().sort_index()

order_hour_of_day
0      22758
1      12398
2       7539
3       5474
4       5527
5       9569
6      30529
7      91868
8     178201
9     257812
10    288418
11    284728
12    272841
13    277999
14    283042
15    283639
16    272553
17    228795
18    182912
19    140569
20    104292
21     78109
22     61468
23     40043
Name: count, dtype: int64

In [54]:
#Q5:Understanding missing values in days_since_prior_order
df_orders["days_since_prior_order"].isna().sum()

np.int64(206209)

In [55]:
#Logical check: first orders and null values
df_orders.loc[df_orders["order_number"] == 1, "days_since_prior_order"].isna().all()

np.True_

#### Consistency checks for the orders table

In [56]:
#Is order_id unique?
df_orders["order_id"].is_unique

True

In [57]:
#Is order_dow in the correct range?
df_orders["order_dow"].between(0, 6).all()

np.True_

In [58]:
#Is order_hour_of_day in the correct range?
df_orders["order_hour_of_day"].between(0, 23).all()

np.True_

#### Filtering the orders table to train orders

In [59]:
df_orders_train = df_orders[df_orders["eval_set"] == "train"]
df_orders_train.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,train,11,4,8,14.00
25,1492625,2,train,15,1,11,30.00
49,2196797,5,train,5,0,11,6.00
74,525192,7,train,21,2,11,6.00
78,880375,8,train,4,1,14,10.00

In [60]:
#Keeping only the columns we need
df_orders_train.drop(columns=["eval_set"])
df_orders_train.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,train,11,4,8,14.00
25,1492625,2,train,15,1,11,30.00
49,2196797,5,train,5,0,11,6.00
74,525192,7,train,21,2,11,6.00
78,880375,8,train,4,1,14,10.00

In [61]:
del df_orders

##### Exploring the order_products_train Table

In [62]:
#Previewing the data
df_orders_products_train.head()

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [63]:
#Inspecting the schema
df_orders_products_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 1384617 entries, 0 to 1384616
Data columns (total 4 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   order_id           1384617 non-null  int64
 1   product_id         1384617 non-null  int64
 2   add_to_cart_order  1384617 non-null  int64
 3   reordered          1384617 non-null  int64
dtypes: int64(4)
memory usage: 42.3 MB

In [64]:
#Looking at data types
df_orders_products_train.dtypes

order_id             int64
product_id           int64
add_to_cart_order    int64
reordered            int64
dtype: object

In [65]:
#Descriptive statistics
df_orders_products_train.describe()

          order_id   product_id  add_to_cart_order    reordered
count 1,384,617.00 1,384,617.00       1,384,617.00 1,384,617.00
mean  1,706,297.62    25,556.24               8.76         0.60
std     989,732.65    14,121.27               7.42         0.49
min           1.00         1.00               1.00         0.00
25%     843,370.00    13,380.00               3.00         0.00
50%   1,701,880.00    25,298.00               7.00         1.00
75%   2,568,023.00    37,940.00              12.00         1.00
max   3,421,070.00    49,688.00              80.00         1.00

In [66]:
#Missing values
df_orders_products_train.isna().sum()

order_id             0
product_id           0
add_to_cart_order    0
reordered            0
dtype: int64

In [67]:
#Q1: How many line items exist?
len(df_orders_products_train)

1384617

In [68]:
#Q2: How many unique orders are represented in this table?
df_orders_products_train["order_id"].nunique()

131209

In [69]:
#Q3: How many unique products are represented in this table?
df_orders_products_train["product_id"].nunique()

39123

In [70]:
#Q4: Exploring reorder behavior
df_orders_products_train["reordered"].value_counts(dropna=False)

reordered
1    828824
0    555793
Name: count, dtype: int64

In [71]:
#Q5: Reorder share
df_orders_products_train["reordered"].value_counts(normalize=False)

reordered
1    828824
0    555793
Name: count, dtype: int64

In [72]:
df_orders_products_train["reordered"].value_counts(normalize=True)

reordered
1   0.60
0   0.40
Name: proportion, dtype: float64

In [73]:
#Q6: Understanding add_to_cart_order
df_orders_products_train["add_to_cart_order"].describe()

count   1,384,617.00
mean            8.76
std             7.42
min             1.00
25%             3.00
50%             7.00
75%            12.00
max            80.00
Name: add_to_cart_order, dtype: float64

In [74]:
#Q7: Which cart positions appear most often?
df_orders_products_train["add_to_cart_order"].value_counts().sort_index().head(20)

add_to_cart_order
1     131209
2     124364
3     116996
4     108963
5     100745
6      91850
7      83142
8      74601
9      66618
10     59401
11     52848
12     46814
13     41431
14     36588
15     32194
16     28363
17     24841
18     21733
19     19014
20     16541
Name: count, dtype: int64

In [75]:
#Understanding repeated keys in the table
df_orders_products_train["order_id"].is_unique

False

In [76]:
df_orders_products_train["product_id"].is_unique

False

#### Consistency checks for the order_products_train table

In [77]:
#Is reordered limited to valid values?
df_orders_products_train["reordered"].isin([0, 1]).all()

np.True_

In [78]:
#Is add_to_cart_order positive?
(df_orders_products_train["add_to_cart_order"] > 0).all()

np.True_

In [79]:
#Are there missing values in the key columns?
df_orders_products_train[["order_id", "product_id"]].isna().sum()

order_id      0
product_id    0
dtype: int64

#### Exploring the products Table

In [80]:
#Previewing the data
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.80
1,2,All-Seasons Salt,104,13,9.30
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50
4,5,Green Chile Anytime Sauce,5,13,4.30

In [81]:
#Inspecting the schema
df_products.info()

<class 'pandas.DataFrame'>
Index: 49686 entries, 0 to 49692
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     49686 non-null  int64
 1   product_name   49670 non-null  str
 2   aisle_id       49686 non-null  int64
 3   department_id  49686 non-null  int64
 4   prices         49686 non-null  float64
dtypes: float64(1), int64(3), str(1)
memory usage: 2.3 MB

In [82]:
#Looking at data types
df_products.dtypes

product_id         int64
product_name         str
aisle_id           int64
department_id      int64
prices           float64
dtype: object

In [83]:
#Descriptive statistics
df_products.describe()

       product_id  aisle_id  department_id    prices
count   49,686.00 49,686.00      49,686.00 49,686.00
mean    24,844.83     67.77          11.73      9.99
std     14,343.89     38.32           5.85    453.55
min          1.00      1.00           1.00      1.00
25%     12,423.25     35.00           7.00      4.10
50%     24,844.50     69.00          13.00      7.10
75%     37,266.75    100.00          17.00     11.20
max     49,688.00    134.00          21.00 99,999.00

In [84]:
#Missing values
df_products.isna().sum()

product_id        0
product_name     16
aisle_id          0
department_id     0
prices            0
dtype: int64

In [85]:
#Q1: How many unique products exist?
df_products["product_id"].nunique()

49686

In [86]:
#Q2: Are product IDs unique?
df_products["product_id"].is_unique

True

In [87]:
#Q3: How many unique departments are referenced in the product table?
df_products["department_id"].nunique()

21

In [88]:
#Q4: How many unique aisles are referenced in the product table?
df_products["aisle_id"].nunique()

134

In [89]:
#Q5: Do some product names repeat?
df_products["product_name"].duplicated().sum()

np.int64(15)

#### Consistency checks for the products table

In [90]:
#Are product_id values unique?
df_products["product_id"].is_unique

True

In [91]:
#Are department_id values missing?
df_products["department_id"].isna().sum()

np.int64(0)

In [92]:
#Are aisle_id values missing?
df_products["aisle_id"].isna().sum()

np.int64(0)

#### Exploring the departments_t Table

In [93]:
#Previewing the data
df_departments.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [94]:
#Inspecting the schema
df_departments.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   department_id  21 non-null     int64
 1   department     21 non-null     str
dtypes: int64(1), str(1)
memory usage: 468.0 bytes

In [95]:
#Looking at data types
df_departments.dtypes

department_id    int64
department         str
dtype: object

In [96]:
#Missing values
df_departments.isna().sum()

department_id    0
department       0
dtype: int64

##### Analytical questions that can be answered from departments_t

In [97]:
#Q1: How many departments exist?
df_departments["department"].nunique()

21

In [98]:
#Q2: Are department_id values unique?
df_departments["department_id"].is_unique

True

In [99]:
#Q3: Are there missing values in the table?
df_departments.isna().sum()

department_id    0
department       0
dtype: int64

#### Exploring the aisles Table

In [100]:
#Previewing the data
df_aisles.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [101]:
#Inspecting the schema
df_aisles.info()

<class 'pandas.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   aisle_id  134 non-null    int64
 1   aisle     134 non-null    str
dtypes: int64(1), str(1)
memory usage: 2.2 KB

In [102]:
#Looking at data types
df_aisles.dtypes

aisle_id    int64
aisle         str
dtype: object

In [103]:
#Missing values
df_aisles.isna().sum()

aisle_id    0
aisle       0
dtype: int64

#### Analytical questions that can be answered from aisles

In [104]:
#Q1: How many aisles exist?
df_aisles["aisle"].nunique()

134

In [105]:
#Q2: Are aisle_id values unique?
df_aisles["aisle_id"].is_unique

True

In [106]:
#Q3: Are there missing values in the table?
df_aisles.isna().sum()

aisle_id    0
aisle       0
dtype: int64

#### Merge

In [107]:
#Performing the merge
df_products_departments = pd.merge(
    df_products,
    df_departments,
    on="department_id",
    how="left"
)

df_products_departments.head()

,product_id,product_name,aisle_id,department_id,prices,department
0,1,Chocolate Sandwich Cookies,61,19,5.80,snacks
1,2,All-Seasons Salt,104,13,9.30,pantry
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen
4,5,Green Chile Anytime Sauce,5,13,4.30,pantry

In [108]:
#Understanding the indicator Argument
df_products_departments_check = pd.merge(
    df_products,
    df_departments,
    on="department_id",
    how="left",
    indicator=True
)

df_products_departments_check.head()

,product_id,product_name,aisle_id,department_id,prices,department,_merge
0,1,Chocolate Sandwich Cookies,61,19,5.80,snacks,both
1,2,All-Seasons Salt,104,13,9.30,pantry,both
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,beverages,both
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen,both
4,5,Green Chile Anytime Sauce,5,13,4.30,pantry,both

In [109]:
#Looking at the indicator results
df_products_departments_check["_merge"].value_counts()

_merge
both          49686
left_only         0
right_only        0
Name: count, dtype: int64

In [110]:
#Investigating unmatched rows
df_products_departments_check[
    df_products_departments_check["_merge"] == "left_only"
].head()

Empty DataFrame
Columns: [product_id, product_name, aisle_id, department_id, prices, department, _merge]
Index: []

In [111]:
#Cleaning the indicator result
df_products_departments = pd.merge(
    df_products,
    df_departments,
    on="department_id",
    how="left"
)

df_products_departments.head()

,product_id,product_name,aisle_id,department_id,prices,department
0,1,Chocolate Sandwich Cookies,61,19,5.80,snacks
1,2,All-Seasons Salt,104,13,9.30,pantry
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen
4,5,Green Chile Anytime Sauce,5,13,4.30,pantry

#### Homework P1: Questions unlocked after the first merge

In [112]:
#Department is already merged
#Number of products by department
df_products_departments["department"].value_counts()

department
personal care      6563
snacks             6264
pantry             5371
beverages          4365
frozen             4007
dairy eggs         3448
household          3085
canned goods       2092
dry goods pasta    1858
produce            1684
bakery             1516
deli               1322
missing            1258
international      1139
breakfast          1115
babies             1080
alcohol            1054
pets                972
meat seafood        907
other               548
bulk                 38
Name: count, dtype: int64

In [113]:
#Aisles merge
df_products_enriched = pd.merge(
    df_products_departments,
    df_aisles,
    on="aisle_id",
    how="left"
)

df_products_enriched.head()

,product_id,product_name,aisle_id,department_id,prices,department,aisle
0,1,Chocolate Sandwich Cookies,61,19,5.80,snacks,cookies cakes
1,2,All-Seasons Salt,104,13,9.30,pantry,spices seasonings
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,beverages,tea
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen,frozen meals
4,5,Green Chile Anytime Sauce,5,13,4.30,pantry,marinades meat preparation

In [114]:
#Checking the second merge with indicator=True
df_products_aisles_check = pd.merge(
    df_products_departments,
    df_aisles,
    on="aisle_id",
    how="left",
    indicator=True
)

df_products_aisles_check["_merge"].value_counts()

_merge
both          49686
left_only         0
right_only        0
Name: count, dtype: int64

In [115]:
#Investigating unmatched aisle rows
df_products_aisles_check[
    df_products_aisles_check["_merge"] == "left_only"
].head()

Empty DataFrame
Columns: [product_id, product_name, aisle_id, department_id, prices, department, aisle, _merge]
Index: []

In [116]:
#Checking row counts
print(df_products.shape)
print(df_products_departments.shape)
print(df_products_enriched.shape)

(49686, 5)
(49686, 6)
(49686, 7)

In [117]:
#Checking uniqueness in lookup tables before merging
df_departments["department_id"].is_unique

True

In [118]:
df_aisles["aisle_id"].is_unique

True

#### Homework P2: Questions unlocked after enriching products

In [119]:
#How many products belong to each department?
df_products_enriched["department"].value_counts()

department
personal care      6563
snacks             6264
pantry             5371
beverages          4365
frozen             4007
dairy eggs         3448
household          3085
canned goods       2092
dry goods pasta    1858
produce            1684
bakery             1516
deli               1322
missing            1258
international      1139
breakfast          1115
babies             1080
alcohol            1054
pets                972
meat seafood        907
other               548
bulk                 38
Name: count, dtype: int64

In [120]:
#How many products belong to each aisle?
df_products_enriched["aisle"].value_counts().head(10)

aisle
missing                 1258
candy chocolate         1246
ice cream ice           1091
vitamins supplements    1038
yogurt                  1026
chips pretzels           989
tea                      894
packaged cheese          890
frozen meals             880
cookies cakes            874
Name: count, dtype: int64

In [121]:
#Which aisles are most populated?
df_products_enriched["aisle"].value_counts().head(5)

aisle
missing                 1258
candy chocolate         1246
ice cream ice           1091
vitamins supplements    1038
yogurt                  1026
Name: count, dtype: int64

In [122]:
#Which departments span the widest variety of products?
df_products_enriched.groupby("department")["product_id"].nunique().sort_values(ascending=False)

department
personal care      6563
snacks             6264
pantry             5371
beverages          4365
frozen             4007
dairy eggs         3448
household          3085
canned goods       2092
dry goods pasta    1858
produce            1684
bakery             1516
deli               1322
missing            1258
international      1139
breakfast          1115
babies             1080
alcohol            1054
pets                972
meat seafood        907
other               548
bulk                 38
Name: product_id, dtype: int64

In [123]:
#How are departments and aisles related?
pd.crosstab(
    df_products_enriched["department"],
    df_products_enriched["aisle"]
)

aisle,air fresheners candles,asian foods,baby accessories,baby bath body care,baby food formula,bakery desserts,baking ingredients,baking supplies decor,beauty,beers coolers,...,spreads,tea,tofu meat alternatives,tortillas flat bread,trail mix snack mix,trash bags liners,vitamins supplements,water seltzer sparkling water,white wines,yogurt
department,,,,,,,,,,,,,,,,,,,,,
alcohol,0,0,0,0,0,0,0,0,0,385,...,0,0,0,0,0,0,0,0,147,0
babies,0,0,44,132,717,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bakery,0,0,0,0,0,297,0,0,0,0,...,0,0,0,241,0,0,0,0,0,0
beverages,0,0,0,0,0,0,0,0,0,0,...,0,894,0,0,0,0,0,344,0,0
breakfast,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bulk,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
canned goods,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
dairy eggs,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1026
deli,0,0,0,0,0,0,0,0,0,0,...,0,0,159,0,0,0,0,0,0,0
dry goods pasta,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
frozen,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
household,355,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,112,0,0,0,0
international,0,605,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
meat seafood,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
missing,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
other,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
pantry,0,0,0,0,0,0,623,290,0,0,...,493,0,0,0,0,0,0,0,0,0
personal care,0,0,0,0,0,0,0,0,178,0,...,0,0,0,0,0,0,1038,0,0,0
pets,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
produce,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
snacks,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,69,0,0,0,0,0

In [125]:
#Inner join
pd.merge(
    df_products,
    df_departments,
    on="department_id",
    how="inner"
).head()

,product_id,product_name,aisle_id,department_id,prices,department
0,1,Chocolate Sandwich Cookies,61,19,5.80,snacks
1,2,All-Seasons Salt,104,13,9.30,pantry
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen
4,5,Green Chile Anytime Sauce,5,13,4.30,pantry

In [126]:
#Left join
pd.merge(
    df_products,
    df_departments,
    on="department_id",
    how="left"
).head()

,product_id,product_name,aisle_id,department_id,prices,department
0,1,Chocolate Sandwich Cookies,61,19,5.80,snacks
1,2,All-Seasons Salt,104,13,9.30,pantry
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.50,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen
4,5,Green Chile Anytime Sauce,5,13,4.30,pantry

In [127]:
#Outer join
pd.merge(
    df_products,
    df_departments,
    on="department_id",
    how="outer",
    indicator=True
).head()

,product_id,product_name,aisle_id,department_id,prices,department,_merge
0,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.50,frozen,both
1,8,Cut Russet Potatoes Steam N' Mash,116,1,1.10,frozen,both
2,12,Chocolate Fudge Layer Cake,119,1,9.40,frozen,both
3,18,Pizza for One Suprema Frozen Pizza,79,1,10.60,frozen,both
4,30,"Three Cheese Ziti, Marinara with Meatballs",38,1,13.80,frozen,both

In [128]:
#Orders train and orders products train merge
df_train_transactions = pd.merge(
    df_orders_train,
    df_orders_products_train,
    on="order_id",
    how="left"
)

df_train_transactions.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered
0,1187899,1,train,11,4,8,14.00,196,1,1
1,1187899,1,train,11,4,8,14.00,25133,2,1
2,1187899,1,train,11,4,8,14.00,38928,3,1
3,1187899,1,train,11,4,8,14.00,26405,4,1
4,1187899,1,train,11,4,8,14.00,39657,5,1

In [129]:
#Checking the merge with indicator=True
df_train_transactions_check = pd.merge(
    df_orders_train,
    df_orders_products_train,
    on="order_id",
    how="left",
    indicator=True
)

df_train_transactions_check.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge
0,1187899,1,train,11,4,8,14.00,196,1,1,both
1,1187899,1,train,11,4,8,14.00,25133,2,1,both
2,1187899,1,train,11,4,8,14.00,38928,3,1,both
3,1187899,1,train,11,4,8,14.00,26405,4,1,both
4,1187899,1,train,11,4,8,14.00,39657,5,1,both

In [130]:
#Inspecting the _merge column
df_train_transactions_check["_merge"].value_counts()

_merge
both          1384617
left_only           0
right_only          0
Name: count, dtype: int64

In [131]:
#Looking at unmatched orders
df_train_transactions_check[
    df_train_transactions_check["_merge"] == "left_only"
].head()

Empty DataFrame
Columns: [order_id, user_id, eval_set, order_number, order_dow, order_hour_of_day, days_since_prior_order, product_id, add_to_cart_order, reordered, _merge]
Index: []

In [132]:
#Checking the row counts
print(df_orders_train.shape)
print(df_orders_products_train.shape)
print(df_train_transactions.shape)

(131209, 7)
(1384617, 4)
(1384617, 10)

In [133]:
#What columns do we now have?
df_train_transactions.columns

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order', 'product_id',
       'add_to_cart_order', 'reordered'],
      dtype='str')

In [138]:
#How many items are there in each order?
items_per_order = df_train_transactions.groupby("order_id")["product_id"].count()
items_per_order.head()

order_id
1      8
36     8
38     9
96     7
98    49
Name: product_id, dtype: int64

In [139]:
#Do some days tend to have larger baskets?
avg_items_per_day = df_train_transactions.groupby("order_dow")["product_id"].count() / df_train_transactions.groupby("order_dow")["order_id"].nunique()
avg_items_per_day

order_dow
0   11.80
1   10.47
2    9.96
3    9.84
4    9.74
5   10.16
6   10.97
dtype: float64

In [140]:
#At what hour do larger baskets appear?
avg_items_per_hour = df_train_transactions.groupby("order_hour_of_day")["product_id"].count() / df_train_transactions.groupby("order_hour_of_day")["order_id"].nunique()
avg_items_per_hour

order_hour_of_day
0    10.66
1    11.10
2    10.58
3    10.93
4    11.15
5     9.57
6    10.57
7    10.75
8    10.62
9    10.39
10   10.44
11   10.76
12   10.52
13   10.71
14   10.75
15   10.49
16   10.50
17   10.37
18   10.12
19   10.17
20   10.29
21   11.41
22   11.19
23   11.12
dtype: float64

In [141]:
#Does reorder behavior vary by order timing?
reorder_by_hour = df_train_transactions.groupby("order_hour_of_day")["reordered"].mean()
reorder_by_hour

order_hour_of_day
0    0.57
1    0.58
2    0.58
3    0.58
4    0.60
5    0.62
6    0.65
7    0.65
8    0.64
9    0.62
10   0.61
11   0.59
12   0.59
13   0.59
14   0.59
15   0.58
16   0.59
17   0.59
18   0.58
19   0.59
20   0.60
21   0.61
22   0.60
23   0.59
Name: reordered, dtype: float64

#### Homework P3: Questions unlocked after this merge

In [147]:
#After merging orders_train with order_products_train, we can now answer questions such as:
#How many products are included in each order?
df_train_transactions.groupby("order_id").size().head()

order_id
1      8
36     8
38     9
96     7
98    49
dtype: int64

In [148]:
#What is the typical basket size?
df_train_transactions.groupby("order_id").size().describe()

count   131,209.00
mean         10.55
std           7.93
min           1.00
25%           5.00
50%           9.00
75%          14.00
max          80.00
dtype: float64

In [149]:
#Are larger baskets more common on specific days?
df_train_transactions.groupby("order_dow").size() / df_train_transactions["order_id"].nunique()

order_dow
0   2.47
1   1.57
2   1.22
3   1.18
4   1.18
5   1.35
6   1.58
dtype: float64

In [150]:
#The expression above is only a quick exploratory step. 
#A more careful calculation groups at the order level first and then averages by day.

basket_size_by_order = (
    df_train_transactions
    .groupby(["order_id", "order_dow"])
    .size()
    .reset_index(name="basket_size")
)

basket_size_by_order.groupby("order_dow")["basket_size"].mean()

order_dow
0   11.80
1   10.47
2    9.96
3    9.84
4    9.74
5   10.16
6   10.97
Name: basket_size, dtype: float64

In [151]:
#Are reordered items more common at certain times of day?
df_train_transactions.groupby("order_hour_of_day")["reordered"].mean()

order_hour_of_day
0    0.57
1    0.58
2    0.58
3    0.58
4    0.60
5    0.62
6    0.65
7    0.65
8    0.64
9    0.62
10   0.61
11   0.59
12   0.59
13   0.59
14   0.59
15   0.58
16   0.59
17   0.59
18   0.58
19   0.59
20   0.60
21   0.61
22   0.60
23   0.59
Name: reordered, dtype: float64

In [155]:
#Does basket construction differ across customer order sequence?
# Does basket construction differ across customer order sequence?
avg_basket_by_order_number = df_train_transactions.groupby("order_number")["product_id"].mean()
avg_basket_by_order_number

order_number
4     25,521.34
5     25,576.31
6     25,604.94
7     25,598.50
8     25,549.66
         ...
96    25,993.66
97    24,782.55
98    25,296.67
99    24,714.95
100   25,443.50
Name: product_id, Length: 97, dtype: float64

In [152]:
#Are there missing product_id values after the merge?
df_train_transactions["product_id"].isna().sum()

np.int64(0)

In [153]:
#Are there missing user_id values after the merge?
df_train_transactions["user_id"].isna().sum()

np.int64(0)

In [154]:
#Does every row now represent an order-product combination?
df_train_transactions["order_id"].value_counts().head()

order_id
2813632    80
1395075    80
949182     77
2869702    76
341238     76
Name: count, dtype: int64

In [156]:
#The last step is to merge df_train_transactions with df_products_enriched.
df_train_analytic = pd.merge(
    df_train_transactions,
    df_products_enriched,
    on="product_id",
    how="left"
)

df_train_analytic.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,department,aisle
0,1187899,1,train,11,4,8,14.00,196,1,1,Soda,77.00,7.00,9.00,beverages,soft drinks
1,1187899,1,train,11,4,8,14.00,25133,2,1,Organic String Cheese,21.00,16.00,8.60,dairy eggs,packaged cheese
2,1187899,1,train,11,4,8,14.00,38928,3,1,0% Greek Strained Yogurt,120.00,16.00,12.60,dairy eggs,yogurt
3,1187899,1,train,11,4,8,14.00,26405,4,1,XL Pick-A-Size Paper Towel Rolls,54.00,17.00,1.00,household,paper goods
4,1187899,1,train,11,4,8,14.00,39657,5,1,Milk Chocolate Almonds,45.00,19.00,6.80,snacks,candy chocolate

In [157]:
#Checking the final merge with indicator=True
df_train_analytic_check = pd.merge(
    df_train_transactions,
    df_products_enriched,
    on="product_id",
    how="left",
    indicator=True
)

df_train_analytic_check["_merge"].value_counts()

_merge
both          1384529
left_only          88
right_only          0
Name: count, dtype: int64

In [158]:
#Investigating unmatched product rows
df_train_analytic_check[
    df_train_analytic_check["_merge"] == "left_only"
].head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,department,aisle,_merge
10778,3009052,1629,train,37,0,13,3.00,6799,24,1,NaN,NaN,NaN,NaN,NaN,NaN,left_only
52811,195363,7955,train,12,6,14,8.00,6799,4,1,NaN,NaN,NaN,NaN,NaN,NaN,left_only
59737,831974,9000,train,11,3,13,20.00,6799,19,0,NaN,NaN,NaN,NaN,NaN,NaN,left_only
64147,206208,9640,train,16,6,11,12.00,6799,6,1,NaN,NaN,NaN,NaN,NaN,NaN,left_only
81571,472316,12168,train,10,4,12,0.00,6799,12,1,NaN,NaN,NaN,NaN,NaN,NaN,left_only

#### Homework P4 Questions unlocked after the final merge