In [11]:
# Import pandas library for data manipulation
import pandas as pd

In [12]:
data = ['customers.csv', 'states.csv']

URL = 'https://raw.githubusercontent.com/hovhannisyan91/aca/refs/heads/main/lab/python/data/raw/'

ldf = []
for i in data: 
    df = pd.read_csv(URL+i)
    # քանի որ ցանկանում ենք նաև միացնել տվյալները մենք կարող ենք դա անել միանգամից՝ նախ սկզբում պահելով այն լիստի մեջ
    ldf.append(df)

In [13]:
df_customers = ldf[0]
df_states = ldf[1]

In [14]:
df_states.head()

           state     region     division
0    Connecticut  Northeast  New England
1          Maine  Northeast  New England
2  Massachusetts  Northeast  New England
3  New Hampshire  Northeast  New England
4   Rhode Island  Northeast  New England

In [15]:
df_customers.head()

,user_id,First Name,Surnam,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

In [16]:
df_customers.rename(columns={'STATE':'state'}, inplace=True)

In [17]:
df_customers_states = df_customers.merge(df_states,on = 'state')

In [18]:
df_customers_states.head()

,user_id,First Name,Surnam,Gender,state,Age,date_joined,n_dependants,fam_status,income,region,division
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665,Midwest,West North Central
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285,West,Mountain
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568,West,Mountain
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049,Midwest,West North Central
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374,South,South Atlantic

In [27]:
df_train_analytic = pd.read_csv("../data/processed/train_analytic.csv", index_col=0)

In [28]:
df_train_analytic.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,department,aisle
0,1187899,1,train,11,4,8,14.0,196,1,1,Soda,77.0,7.0,9.0,beverages,soft drinks
1,1187899,1,train,11,4,8,14.0,25133,2,1,Organic String Cheese,21.0,16.0,8.6,dairy eggs,packaged cheese
2,1187899,1,train,11,4,8,14.0,38928,3,1,0% Greek Strained Yogurt,120.0,16.0,12.6,dairy eggs,yogurt
3,1187899,1,train,11,4,8,14.0,26405,4,1,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,household,paper goods
4,1187899,1,train,11,4,8,14.0,39657,5,1,Milk Chocolate Almonds,45.0,19.0,6.8,snacks,candy chocolate

In [ ]:
df_train_analytics_final = df_train_analytic.merge(
    df_customers_states, 
    on='user_id', 
    how='left')
df_train_analytics_final.drop(columns='user_id',inplace=True)

In [30]:
df_train_analytics_final.head()

,order_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,Surnam,Gender,state,Age,date_joined,n_dependants,fam_status,income,region,division
0,1187899,train,11,4,8,14.0,196,1,1,Soda,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
1,1187899,train,11,4,8,14.0,25133,2,1,Organic String Cheese,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
2,1187899,train,11,4,8,14.0,38928,3,1,0% Greek Strained Yogurt,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
3,1187899,train,11,4,8,14.0,26405,4,1,XL Pick-A-Size Paper Towel Rolls,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
4,1187899,train,11,4,8,14.0,39657,5,1,Milk Chocolate Almonds,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central

In [31]:
df_train_analytics_final.shape

(1384706, 26)

In [32]:
df_train_analytics_final.head()

,order_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,Surnam,Gender,state,Age,date_joined,n_dependants,fam_status,income,region,division
0,1187899,train,11,4,8,14.0,196,1,1,Soda,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
1,1187899,train,11,4,8,14.0,25133,2,1,Organic String Cheese,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
2,1187899,train,11,4,8,14.0,38928,3,1,0% Greek Strained Yogurt,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
3,1187899,train,11,4,8,14.0,26405,4,1,XL Pick-A-Size Paper Towel Rolls,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
4,1187899,train,11,4,8,14.0,39657,5,1,Milk Chocolate Almonds,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central

In [33]:
df_train_analytics_final.to_csv("../data/processed/instacart.csv",index= False)