In [109]:
from datetime import datetime, date, timedelta

In [110]:
simple_date = date(2024, 7, 1)
simple_date

datetime.date(2024, 7, 1)

In [111]:
full_datetime = datetime(2024, 7, 1, 14, 30, 0)
full_datetime

datetime.datetime(2024, 7, 1, 14, 30)

In [112]:
today = date.today()
now = datetime.now()

print(f'today is {today}')
print(f'right now is {now}')

today is 2026-04-03
right now is 2026-04-03 17:49:53.710461

In [113]:
name = "Mari"
print(f'Hello {name}')

Hello Mari

In [114]:
print(f"Day: {full_datetime.day}")

Day: 1

In [115]:
print(f"Year: {full_datetime.year}")
print(f"Month: {full_datetime.month}")
print(f"Day: {full_datetime.day}")
print(f"Hour: {full_datetime.hour}")
print(f"Minute: {full_datetime.minute}")
print(f"Second: {full_datetime.second}")

Year: 2024
Month: 7
Day: 1
Hour: 14
Minute: 30
Second: 0

In [116]:
full_datetime.strftime("%Y-%m-%d")

'2024-07-01'

In [117]:
full_datetime.strftime("%d/%m/%Y")

'01/07/2024'

In [118]:
full_datetime.strftime("%B %d, %Y")

'July 01, 2024'

In [119]:
dt = datetime.strptime("2024-07-01", "%Y-%m-%d")
dt

datetime.datetime(2024, 7, 1, 0, 0)

In [120]:
start = date(2024, 7, 1)
end = date(2024, 7, 15)

delta = end - start
delta

datetime.timedelta(days=14)

In [121]:
delta.days

14

In [122]:
start + timedelta(days=10)

datetime.date(2024, 7, 11)

In [123]:
start - timedelta(days=7)

datetime.date(2024, 6, 24)

In [124]:
print(start + timedelta(days=10))
print(start - timedelta(days=7))
print(start + timedelta(weeks=2))
print(start - timedelta(weeks=1))

2024-07-11
2024-06-24
2024-07-15
2024-06-24

In [125]:
start_dt = datetime(2024, 7, 1, 14, 30, 0)

print(start_dt + timedelta(days=1))
print(start_dt + timedelta(hours=5))
print(start_dt + timedelta(minutes=45))
print(start_dt + timedelta(seconds=30))
print(start_dt + timedelta(days=2, hours=3, minutes=15, seconds=10))

2024-07-02 14:30:00
2024-07-01 19:30:00
2024-07-01 15:15:00
2024-07-01 14:30:30
2024-07-03 17:45:10

In [126]:
import pandas as pd

df_dates = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105],
    "signup_date": ["2024-01-15", "2024-02-20", "2024-03-05", "2024-03-18", "2024-04-10"],
    "last_purchase": ["2024-06-01", "2024-06-15", "2024-07-01", "2024-07-08", "2024-07-12"]
})

df_dates

   customer_id signup_date last_purchase
0          101  2024-01-15    2024-06-01
1          102  2024-02-20    2024-06-15
2          103  2024-03-05    2024-07-01
3          104  2024-03-18    2024-07-08
4          105  2024-04-10    2024-07-12

In [127]:
df_dates.dtypes

customer_id      int64
signup_date        str
last_purchase      str
dtype: object

In [128]:
#Converting to Datetime
df_dates["signup_date"] = pd.to_datetime(df_dates["signup_date"])
df_dates["last_purchase"] = pd.to_datetime(df_dates["last_purchase"])

df_dates.dtypes

customer_id               int64
signup_date      datetime64[us]
last_purchase    datetime64[us]
dtype: object

In [129]:
#Year, Month, and Day
df_dates["signup_year"] = df_dates["signup_date"].dt.year
df_dates["signup_month"] = df_dates["signup_date"].dt.month
df_dates["signup_day"] = df_dates["signup_date"].dt.day

df_dates

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day
0,101,2024-01-15,2024-06-01,2024,1,15
1,102,2024-02-20,2024-06-15,2024,2,20
2,103,2024-03-05,2024-07-01,2024,3,5
3,104,2024-03-18,2024-07-08,2024,3,18
4,105,2024-04-10,2024-07-12,2024,4,10

In [130]:
#Month Name and Day Name
df_dates["signup_month_name"] = df_dates["signup_date"].dt.month_name()
df_dates["signup_day_name"] = df_dates["signup_date"].dt.day_name()

df_dates[["signup_date", "signup_month_name", "signup_day_name"]]

  signup_date signup_month_name signup_day_name
0  2024-01-15           January          Monday
1  2024-02-20          February         Tuesday
2  2024-03-05             March         Tuesday
3  2024-03-18             March          Monday
4  2024-04-10             April       Wednesday

In [131]:
#Quarter
df_dates["signup_quarter"] = df_dates["signup_date"].dt.quarter
df_dates[["signup_date", "signup_quarter"]]

  signup_date  signup_quarter
0  2024-01-15               1
1  2024-02-20               1
2  2024-03-05               1
3  2024-03-18               1
4  2024-04-10               2

In [132]:
#Day of week
df_dates["signup_dow"] = df_dates["signup_date"].dt.dayofweek
df_dates[["signup_date", "signup_dow"]]

  signup_date  signup_dow
0  2024-01-15           0
1  2024-02-20           1
2  2024-03-05           1
3  2024-03-18           0
4  2024-04-10           2

In [133]:
#Weekend Flag
df_dates["is_weekend"] = (df_dates["signup_date"].dt.dayofweek >5).astype(int)
df_dates[["signup_date", "signup_dow", "is_weekend"]]

  signup_date  signup_dow  is_weekend
0  2024-01-15           0           0
1  2024-02-20           1           0
2  2024-03-05           1           0
3  2024-03-18           0           0
4  2024-04-10           2           0

In [134]:
#Calculating Differences Between Dates
df_dates["days_between_signup_and_purchase"] = (
    df_dates["last_purchase"] - df_dates["signup_date"]   
).dt.days

df_dates[["signup_date", "last_purchase", "days_between_signup_and_purchase"]]

  signup_date last_purchase  days_between_signup_and_purchase
0  2024-01-15    2024-06-01                               138
1  2024-02-20    2024-06-15                               116
2  2024-03-05    2024-07-01                               118
3  2024-03-18    2024-07-08                               112
4  2024-04-10    2024-07-12                                93

In [135]:
#Filtering by Date Conditions
#Filter Rows After a Given Date
df_dates[df_dates["signup_date"] >= "2024-03-01"]

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase
2,103,2024-03-05,2024-07-01,2024,3,5,March,Tuesday,1,1,0,118
3,104,2024-03-18,2024-07-08,2024,3,18,March,Monday,1,0,0,112
4,105,2024-04-10,2024-07-12,2024,4,10,April,Wednesday,2,2,0,93

In [136]:
#Filter a Specific Month
df_dates[df_dates["signup_date"].dt.month == 3]

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase
2,103,2024-03-05,2024-07-01,2024,3,5,March,Tuesday,1,1,0,118
3,104,2024-03-18,2024-07-08,2024,3,18,March,Monday,1,0,0,112

In [137]:
#Filter a Specific Year
df_dates[df_dates["signup_date"].dt.year == 2024]

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase
0,101,2024-01-15,2024-06-01,2024,1,15,January,Monday,1,0,0,138
1,102,2024-02-20,2024-06-15,2024,2,20,February,Tuesday,1,1,0,116
2,103,2024-03-05,2024-07-01,2024,3,5,March,Tuesday,1,1,0,118
3,104,2024-03-18,2024-07-08,2024,3,18,March,Monday,1,0,0,112
4,105,2024-04-10,2024-07-12,2024,4,10,April,Wednesday,2,2,0,93

In [138]:
#Sorting by Date
df_dates.sort_values("signup_date")

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase
0,101,2024-01-15,2024-06-01,2024,1,15,January,Monday,1,0,0,138
1,102,2024-02-20,2024-06-15,2024,2,20,February,Tuesday,1,1,0,116
2,103,2024-03-05,2024-07-01,2024,3,5,March,Tuesday,1,1,0,118
3,104,2024-03-18,2024-07-08,2024,3,18,March,Monday,1,0,0,112
4,105,2024-04-10,2024-07-12,2024,4,10,April,Wednesday,2,2,0,93

In [139]:
#Creating Date Ranges
#Daily Date Range
pd.date_range(start="2024-07-01", periods=7, freq="D")

DatetimeIndex(['2024-07-01', '2024-07-02', '2024-07-03', '2024-07-04',
               '2024-07-05', '2024-07-06', '2024-07-07'],
              dtype='datetime64[us]', freq='D')

In [140]:
#Monthly Date Range

In [141]:
#Begining and the End of Month
some_date = pd.Timestamp("2024-07-15")

print(f"Original date: {some_date}")
print(f"Beginning of month: {some_date.to_period('M').start_time}")
print(f"End of month: {some_date.to_period('M').end_time}")

Original date: 2024-07-15 00:00:00
Beginning of month: 2024-07-01 00:00:00
End of month: 2024-07-31 23:59:59.999999

In [142]:
print(f"Beginning of month (date only): {some_date.to_period('M').start_time.date()}")
print(f"End of month (date only): {some_date.to_period('M').end_time.date()}")

Beginning of month (date only): 2024-07-01
End of month (date only): 2024-07-31

In [143]:
df_dates["signup_month"] = df_dates["signup_date"].dt.to_period("M").dt.start_time
df_dates["signup_month"] = df_dates["signup_date"].dt.to_period("M").dt.end_time

df_dates

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase
0,101,2024-01-15,2024-06-01,2024,2024-01-31 23:59:59.999999,15,January,Monday,1,0,0,138
1,102,2024-02-20,2024-06-15,2024,2024-02-29 23:59:59.999999,20,February,Tuesday,1,1,0,116
2,103,2024-03-05,2024-07-01,2024,2024-03-31 23:59:59.999999,5,March,Tuesday,1,1,0,118
3,104,2024-03-18,2024-07-08,2024,2024-03-31 23:59:59.999999,18,March,Monday,1,0,0,112
4,105,2024-04-10,2024-07-12,2024,2024-04-30 23:59:59.999999,10,April,Wednesday,2,2,0,93

#### Homework

In [144]:
#1.create date object
my_date = date(2025, 3, 15)
print(my_date)

2025-03-15

In [145]:
# print components
print(f"Full date: {my_date}")
print(f"Year: {my_date.year}")
print(f"Month: {my_date.month}")
print(f"Day: {my_date.day}")

Full date: 2025-03-15
Year: 2025
Month: 3
Day: 15

In [146]:
#2.Create a datetime Object and name it meeting_time
meeting_time = datetime(2025, 10, 8, 16, 45, 30)
print(meeting_time)

2025-10-08 16:45:30

In [147]:
print(f"Year: {meeting_time.year}")
print(f"Month {meeting_time.month}")
print(f"Day: {meeting_time.day}")
print(f"Hour: {meeting_time.minute}")
print(f"Second: {meeting_time.second}")

Year: 2025
Month 10
Day: 8
Hour: 45
Second: 30

In [148]:
#3. Format Dates as Strings using meeting_time, display the date in the following formats:
meeting_time.strftime("%Y-%m-%d")

'2025-10-08'

In [149]:
meeting_time.strftime("%d/%m/%y")

'08/10/25'

In [150]:
meeting_time.strftime("%B %d, %Y")

'October 08, 2025'

In [151]:
#4.Parse a String into a Datetime
dt = datetime.strptime("2025-12-31", "%Y-%m-%d")

In [152]:
print(f"Parsed datetime: {dt}")

Parsed datetime: 2025-12-31 00:00:00

In [153]:
#5.Date Arithmetic
start = date(2025, 1, 10)
end = date(2025, 2, 5)

difference = end - start

In [154]:
print(f"Days difference: {difference.days}")

Days difference: 26

In [155]:
#6.Work with timedelta Using start, calculate and print with f-strings
# date calculations
print(f"10 days after start: {start + timedelta(days=10)}")
print(f"14 days before start: {start - timedelta(days=14)}")
print(f"3 weeks after start: {start + timedelta(weeks=3)}")

10 days after start: 2025-01-20
14 days before start: 2024-12-27
3 weeks after start: 2025-01-31

In [156]:
#Then create a datetime object and add:
dt = datetime(2025, 1, 10, 12, 0, 0)

In [157]:
new_dt = dt + timedelta(hours=5, minutes=20, seconds=45)

In [158]:
print(f"Updated datetime: {new_dt}")

Updated datetime: 2025-01-10 17:20:45

#### Practice with Pandas Dates

In [190]:
#1.Create a DataFrame with Date Strings
df_sales = pd.DataFrame({
    "customer_id": [1, 2, 3, 4, 5],
    "signup_date": ["2024-01-10", "2024-02-05", "2024-03-12", "2024-04-01", "2024-05-20"],
    "last_purchase": ["2024-02-15", "2024-03-01", "2024-03-28","2024-05-10", "2024-06-25" ]
})

df_sales

   customer_id signup_date last_purchase
0            1  2024-01-10    2024-02-15
1            2  2024-02-05    2024-03-01
2            3  2024-03-12    2024-03-28
3            4  2024-04-01    2024-05-10
4            5  2024-05-20    2024-06-25

In [191]:
#2.Check the data types of all columns.
print(df_sales.dtypes)

customer_id      int64
signup_date        str
last_purchase      str
dtype: object

In [195]:
#3.Convert String Columns to Datetime
df_sales['signup_date'] = pd.to_datetime(df_sales['signup_date'])

In [193]:
#4.convert signup_date into proper datetime columns
#5.convert last_purchase into proper datetime columns

df_sales["signup_date"] = pd.to_datetime(df_sales["signup_date"])

In [162]:
df_sales["last_purchase"] = pd.to_datetime(df_sales["last_purchase"])

In [163]:
#6.Then print the data types again. (you must see pd.datetime instead of )
print(df_sales.dtypes)

customer_id               int64
signup_date      datetime64[us]
last_purchase    datetime64[us]
dtype: object

In [164]:
#7.Extract Date Components signup_date
df_sales["signup_year"] = df_sales["signup_date"].dt.year
df_sales["signup_month"] = df_sales["signup_date"].dt.month
df_sales["signup_day"] = df_sales["signup_date"].dt.day
df_sales["signup_quarter"] = df_sales["signup_date"].dt.quarter
df_sales["signup_month_name"] = df_sales["signup_date"].dt.month_name()
df_sales["signup_day_name"] = df_sales["signup_date"].dt.day_name()

df_sales

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_quarter,signup_month_name,signup_day_name
0,1,2024-01-10,2024-02-15,2024,1,10,1,January,Wednesday
1,2,2024-02-05,2024-03-01,2024,2,5,1,February,Monday
2,3,2024-03-12,2024-03-28,2024,3,12,1,March,Tuesday
3,4,2024-04-01,2024-05-10,2024,4,1,2,April,Monday
4,5,2024-05-20,2024-06-25,2024,5,20,2,May,Monday

In [165]:
#8. Create a Day-of-Week 
# signup_dow using .dt.dayofweek
df_sales["signup_dow"] = df_sales["signup_date"].dt.dayofweek

In [166]:
#Weekend Flag
#is_weekend where weekend = 1 and weekday = 0
df_sales["is_weekend"] = (df_sales["signup_date"].dt.dayofweek >= 5).astype(int)

In [167]:
# Check result
df_sales[["signup_date", "signup_dow", "is_weekend"]]

  signup_date  signup_dow  is_weekend
0  2024-01-10           2           0
1  2024-02-05           0           0
2  2024-03-12           1           0
3  2024-04-01           0           0
4  2024-05-20           0           0

In [168]:
#9.Create a new column called days_between_signup_and_purchase. It should show the number of days between signup_date and last_purchase.
df_sales["days_between_signup_and_purchase"] = (
    df_sales["last_purchase"] - df_sales["signup_date"]
).dt.days

In [169]:
#check result
print(df_sales[["signup_date", "last_purchase", "days_between_signup_and_purchase"]])

  signup_date last_purchase  days_between_signup_and_purchase
0  2024-01-10    2024-02-15                                36
1  2024-02-05    2024-03-01                                25
2  2024-03-12    2024-03-28                                16
3  2024-04-01    2024-05-10                                39
4  2024-05-20    2024-06-25                                36

In [170]:
#10.Filter Date: customers who signed up after "2024-03-01"
df_after = df_sales[df_sales["signup_date"] > "2024-03-01"]
print(df_after)

   customer_id signup_date last_purchase  signup_year  signup_month  \
2            3  2024-03-12    2024-03-28         2024             3
3            4  2024-04-01    2024-05-10         2024             4
4            5  2024-05-20    2024-06-25         2024             5

   signup_day  signup_quarter signup_month_name signup_day_name  signup_dow  \
2          12               1             March         Tuesday           1
3           1               2             April          Monday           0
4          20               2               May          Monday           0

   is_weekend  days_between_signup_and_purchase
2           0                                16
3           0                                39
4           0                                36

In [171]:
#customers who signed up in March
df_march = df_sales[df_sales["signup_date"].dt.month == 3]
print(df_march)

   customer_id signup_date last_purchase  signup_year  signup_month  \
2            3  2024-03-12    2024-03-28         2024             3

   signup_day  signup_quarter signup_month_name signup_day_name  signup_dow  \
2          12               1             March         Tuesday           1

   is_weekend  days_between_signup_and_purchase
2           0                                16

In [172]:
#customers who signed up in 2024
df_2024 = df_sales[df_sales["signup_date"].dt.year == 2024]
print(df_2024)

   customer_id signup_date last_purchase  signup_year  signup_month  \
0            1  2024-01-10    2024-02-15         2024             1
1            2  2024-02-05    2024-03-01         2024             2
2            3  2024-03-12    2024-03-28         2024             3
3            4  2024-04-01    2024-05-10         2024             4
4            5  2024-05-20    2024-06-25         2024             5

   signup_day  signup_quarter signup_month_name signup_day_name  signup_dow  \
0          10               1           January       Wednesday           2
1           5               1          February          Monday           0
2          12               1             March         Tuesday           1
3           1               2             April          Monday           0
4          20               2               May          Monday           0

   is_weekend  days_between_signup_and_purchase
0           0                                36
1           0                                25
2           0                                16
3           0                                39
4           0                                36

In [173]:
#11. Sort by Date: Sort the DataFrame by signup_date from earliest to lastest.
df_sales.sort_values("signup_date")

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_quarter,signup_month_name,signup_day_name,signup_dow,is_weekend,days_between_signup_and_purchase
0,1,2024-01-10,2024-02-15,2024,1,10,1,January,Wednesday,2,0,36
1,2,2024-02-05,2024-03-01,2024,2,5,1,February,Monday,0,0,25
2,3,2024-03-12,2024-03-28,2024,3,12,1,March,Tuesday,1,0,16
3,4,2024-04-01,2024-05-10,2024,4,1,2,April,Monday,0,0,39
4,5,2024-05-20,2024-06-25,2024,5,20,2,May,Monday,0,0,36

In [174]:
#12.Generate a daily date range starting from "2024-07-01" for 10 days.
date_range = pd.date_range(start="2024-07-01", periods=10, freq="D")
print(date_range)

DatetimeIndex(['2024-07-01', '2024-07-02', '2024-07-03', '2024-07-04',
               '2024-07-05', '2024-07-06', '2024-07-07', '2024-07-08',
               '2024-07-09', '2024-07-10'],
              dtype='datetime64[us]', freq='D')

In [175]:
#13.Generate a monthly date range starting from "2024-01-01" for 12 months using month start frequency.
date_range = pd.date_range(start="2024-01-01", periods=12, freq="MS")
print(date_range)

DatetimeIndex(['2024-01-01', '2024-02-01', '2024-03-01', '2024-04-01',
               '2024-05-01', '2024-06-01', '2024-07-01', '2024-08-01',
               '2024-09-01', '2024-10-01', '2024-11-01', '2024-12-01'],
              dtype='datetime64[us]', freq='MS')

In [176]:
#14. Create a DataFrame with: 
#a date columns covering 15 daily dates starting from "2024-01-01"
dates = pd.date_range(start="2024-01-01", periods=15, freq="D")

In [184]:
# create DataFrame
df_sales_new = pd.DataFrame({
    "date": dates,
    "sales": [100, 120, 90, 150, 200, 180, 130, 170, 160, 140, 110, 190, 210, 175, 155]
})

In [185]:
# check result
print(df_sales_new)

         date  sales
0  2024-01-01    100
1  2024-01-02    120
2  2024-01-03     90
3  2024-01-04    150
4  2024-01-05    200
5  2024-01-06    180
6  2024-01-07    130
7  2024-01-08    170
8  2024-01-09    160
9  2024-01-10    140
10 2024-01-11    110
11 2024-01-12    190
12 2024-01-13    210
13 2024-01-14    175
14 2024-01-15    155

In [187]:
#derivative columns
df_sales_new["year"] = df_sales_new["date"].dt.year
df_sales_new["month"] = df_sales_new["date"].dt.month
df_sales_new["day"] = df_sales_new["date"].dt.day
df_sales_new["day_name"] = df_sales_new["date"].dt.day_name()
df_sales_new["dow"] = df_sales_new["date"].dt.dayofweek
df_sales_new["is_weekend"] = (df_sales_new["dow"] >= 5).astype(int)

In [188]:
#15:
some_date = pd.Timestamp("2024-08-18")

print(f"Original date: {some_date}")
print(f"Beginning of month: {some_date.to_period('M').start_time}")
print(f"End of month: {some_date.to_period('M').end_time}")
print(f"Beginning of month (date only): {some_date.to_period('M').start_time.date()}")
print(f"End of month (date only): {some_date.to_period('M').end_time.date()}")

Original date: 2024-08-18 00:00:00
Beginning of month: 2024-08-01 00:00:00
End of month: 2024-08-31 23:59:59.999999
Beginning of month (date only): 2024-08-01
End of month (date only): 2024-08-31

In [189]:
print(df_sales.columns)

Index(['date', 'sales', 'year', 'month', 'day', 'day_name', 'dow',
       'is_weekend'],
      dtype='str')

In [202]:
#16:
# month start
df_sales["month_start"] = df_sales["signup_date"].dt.to_period("M").dt.start_time.dt.date

In [203]:
# month end
df_sales["month_end"] = df_sales["signup_date"].dt.to_period("M").dt.end_time.dt.date

In [204]:
# check result
print(df_sales[["signup_date", "month_start", "month_end"]])

  signup_date month_start   month_end
0  2024-01-10  2024-01-01  2024-01-31
1  2024-02-05  2024-02-01  2024-02-29
2  2024-03-12  2024-03-01  2024-03-31
3  2024-04-01  2024-04-01  2024-04-30
4  2024-05-20  2024-05-01  2024-05-31